#!/usr/bin/env python3
"""
Scientific Validation Test (Metadata-Driven)

Validates: Physical correctness and reasonable ranges of ALL output properties

This comprehensive test dynamically validates ALL output properties based on YAML metadata:
- NaN/Inf Detection: Checks ALL floating-point properties (FAIL if found)
- Zero Value Warnings: Checks ALL numeric properties (WARNING only, respects sentinels)
- Range Validation: Checks properties with defined ranges in YAML (FAIL if violated)

Key Features:
- Fully metadata-driven: validation rules come from property YAML files
- No hardcoded property lists: automatically adapts to property changes
- Sentinel awareness: respects sentinel values (e.g., 0.0, -1.0) in validation

Validation Rules Source:
- Generated from: metadata/*.yaml
- Manifest file: tests/generated/property_ranges.json
- Regenerate: make generate

Note: Internal units are 10^10 Msun/h for masses

"""

import json
import sys
from pathlib import Path

import numpy as np
import yaml

# Add framework to path
REPO_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(REPO_ROOT / "tests"))
sys.path.insert(0, str(REPO_ROOT / "plot" / "mimic-plot"))

from framework import (
    GREEN,
    MIMIC_EXE,
    NC,
    RED,
    TEST_DATA_DIR,
    YELLOW,
    TestSkipped,
    core_input_file,
    ensure_output_dirs,
    find_nonfinite,
    load_binary_halos,
    load_hdf5_halos,
    resolve_sim_config_path,
    run_mimic_fresh,
    run_test_suite,
)
from output_schema import load_schema

# Ensure output directories exist before any tests run
ensure_output_dirs()

# Validation manifest (auto-generated by scripts/generate_properties.py)
VALIDATION_MANIFEST_PATH = REPO_ROOT / "tests" / "generated" / "property_ranges.json"


def gravity_code_units_from_schema(schema):
    """Compute G in Mimic reference units from run-local schema metadata.

    The schema records each reference unit's cgs magnitude (``in_cgs``), so the
    test never hard-codes the basis — it reads exactly what the run wrote.
    """
    reference_units = schema["reference_units"]
    unit_length_cm = reference_units["length"]["in_cgs"]
    unit_mass_g = reference_units["mass"]["in_cgs"]
    unit_velocity_cm_per_s = reference_units["velocity"]["in_cgs"]
    unit_time_s = unit_length_cm / unit_velocity_cm_per_s
    gravity_cgs = 6.672e-8
    return gravity_cgs / unit_length_cm**3 * unit_mass_g * unit_time_s**2


# Output regenerated once per process: the fresh-run guard protects against
# stale files from other runs/models, and the first regeneration in this
# process establishes that guarantee for every test in the suite.
_regenerated_output = None
_regenerated_format = None


def selected_package_writes_binary():
    """
    Whether the selected simulation package can produce binary output.

    A snapshot-ordered package cannot: the driver rejects any output format but
    HDF5 at configuration time, so the generated ``test_binary.yaml`` is invalid
    by construction for it and every check below would fail on a run that never
    happened. The effective processing order is read exactly as the parser
    resolves it -- an explicit ``input.processing_order`` in the run file wins,
    otherwise the simulation config the run file points at -- so a package is
    identified by its own declaration rather than by name.
    """
    param_file = core_input_file("test_binary.yaml")
    with open(param_file) as handle:
        config = yaml.safe_load(handle)

    order = (config.get("input") or {}).get("processing_order")
    if order is None:
        sim_config_path = resolve_sim_config_path(config["simulation"]["config"], param_file)
        with open(sim_config_path) as handle:
            sim_config = yaml.safe_load(handle)
        order = ((sim_config or {}).get("input") or {}).get("processing_order")

    return order != "snapshot_ordered"


def regenerate_output():
    """
    Regenerate Mimic output for the selected model and return its path.

    On first call, re-runs Mimic (removing any pre-existing output first) so a
    stale file from a previous run -- possibly produced by a different MODEL
    writing the same shared path -- cannot be validated as if it were this
    run. Subsequent calls in the same process reuse that output.

    Binary output is used wherever the selected package can produce it, which
    keeps the default pair on the format it has always validated. For a package
    that cannot (snapshot-ordered: HDF5-only), the HDF5 configuration is run and
    read instead. Only the vehicle changes -- the checks below are
    format-agnostic and are applied to the same records either way.

    Returns:
        Path: Path to output file
    """
    global _regenerated_output, _regenerated_format
    if _regenerated_output is None:
        if selected_package_writes_binary():
            output_file = TEST_DATA_DIR / "output" / "binary" / "model_z0.000_0"
            param_file = core_input_file("test_binary.yaml")
            output_format = "binary"
        else:
            # filenr 0: a snapshot-ordered run writes a single output partition.
            output_file = TEST_DATA_DIR / "output" / "hdf5" / "model_000.hdf5"
            param_file = core_input_file("test_hdf5.yaml")
            output_format = "hdf5"

        run_mimic_fresh(param_file, output_file)
        _regenerated_output = output_file
        _regenerated_format = output_format

    return _regenerated_output


def load_output_halos(output_file):
    """
    Load halos from the output produced by ``regenerate_output()``.

    Dispatches on the format that run actually wrote. Both loaders return the
    same ``(recarray, metadata)`` shape, so every check downstream is identical.
    """
    if _regenerated_format == "hdf5":
        return load_hdf5_halos(output_file)
    return load_binary_halos(output_file)


def check_zeros(halos, manifest):
    """
    Check for zero values in ALL numeric output properties dynamically
    Suppress warnings for properties with sentinels that include 0 or 0.0
    These are warnings, not failures

    Returns:
        dict: Field name -> count and examples
    """
    zero_counts = {}
    props = manifest.get("properties", {})

    # Check all numeric fields in the dtype
    for field in halos.dtype.names:
        data = getattr(halos, field)

        # Only check numeric types (not in vectors for now, to keep output manageable)
        if data.ndim == 1 and data.dtype.kind in ("f", "i"):  # float or int
            # Check if this property has 0/0.0 in sentinels
            spec = props.get(field, {})
            sentinels = set(spec.get("sentinels", []))

            # Skip zero check if 0 or 0.0 is in sentinels (intentional)
            if 0 in sentinels or 0.0 in sentinels:
                continue

            # Check for zeros
            if data.dtype.kind == "f":
                zero_mask = data == 0.0
            else:
                zero_mask = data == 0

            count = np.sum(zero_mask)
            if count > 0:
                indices = np.where(zero_mask)[0][:5]
                zero_counts[field] = {
                    "count": count,
                    "examples": [
                        (int(i), float(data[i]) if data.dtype.kind == "f" else int(data[i]))
                        for i in indices
                    ],
                }

    return zero_counts


def check_range(halos, field, min_val, max_val, exclude_zeros=False):
    """
    Check if field values are within expected range

    Args:
        halos: Halo data
        field: Field name
        min_val: Minimum expected value
        max_val: Maximum expected value
        exclude_zeros: If True, don't count zeros as below minimum

    Returns:
        dict: Results with 'passed', counts, examples
    """
    data = getattr(halos, field)

    if exclude_zeros:
        # For range checking, exclude zeros (they're already warned about)
        valid_mask = data != 0.0
        data_to_check = data[valid_mask]
    else:
        data_to_check = data

    below_min = data_to_check < min_val
    above_max = data_to_check > max_val

    count_below = np.sum(below_min)
    count_above = np.sum(above_max)

    result = {
        "passed": count_below == 0 and count_above == 0,
        "min_value": float(np.min(data_to_check)) if len(data_to_check) > 0 else 0.0,
        "max_value": float(np.max(data_to_check)) if len(data_to_check) > 0 else 0.0,
        "count_below": count_below,
        "count_above": count_above,
        "examples_below": [],
        "examples_above": [],
    }

    if count_below > 0:
        if exclude_zeros:
            # Find original indices
            original_indices = np.where(valid_mask)[0]
            below_in_valid = np.where(below_min)[0][:5]
            actual_indices = original_indices[below_in_valid]
        else:
            actual_indices = np.where(below_min)[0][:5]

        result["examples_below"] = [(int(i), float(data[i])) for i in actual_indices]

    if count_above > 0:
        if exclude_zeros:
            original_indices = np.where(valid_mask)[0]
            above_in_valid = np.where(above_max)[0][:5]
            actual_indices = original_indices[above_in_valid]
        else:
            actual_indices = np.where(above_max)[0][:5]

        result["examples_above"] = [(int(i), float(data[i])) for i in actual_indices]

    return result


def load_validation_manifest():
    """
    Load the generated validation manifest consumed by metadata-driven tests.
    """
    if not VALIDATION_MANIFEST_PATH.exists():
        raise FileNotFoundError(f"Validation manifest not found: {VALIDATION_MANIFEST_PATH}")
    with open(VALIDATION_MANIFEST_PATH) as f:
        return json.load(f)


def mass_fields_from_metadata(manifest, output_fields):
    """
    Return scalar mass-like output fields with non-negative declared ranges.
    """
    fields = []
    output_field_set = set(output_fields)
    for field, spec in manifest.get("properties", {}).items():
        units = str(spec.get("units", "")).lower()
        rng = spec.get("range")
        if field not in output_field_set:
            continue
        if spec.get("is_vector", False):
            continue
        if spec.get("type") not in ("float", "double", "int", "long long"):
            continue
        if "msun" not in units:
            continue
        if not rng or rng[0] < 0:
            continue
        fields.append(field)
    return sorted(fields)


def test_numerical_validity():
    """
    Test for NaN and Inf values (critical failures)
    """
    print()
    print("=" * 60)
    print("NUMERICAL VALIDITY (NaN/Inf checks)")
    print("=" * 60)

    if not MIMIC_EXE.exists():
        raise TestSkipped("Mimic not built")

    output_file = regenerate_output()
    halos, metadata = load_output_halos(output_file)
    print(f"Loaded {metadata['TotHalos']} halos from {metadata['Ntrees']} trees\n")

    nonfinite = find_nonfinite(halos)

    if nonfinite["nan"]:
        print(f"{RED}✗ FAIL: Found NaN values in {len(nonfinite['nan'])} field(s):{NC}")
        for field, info in nonfinite["nan"].items():
            print(f"  {field}: {info['count']} NaN values")
            if info["examples"]:
                for idx, val in info["examples"]:
                    print(f"    Halo {idx}: {field} = {val}")
        raise AssertionError(f"NaN values in {len(nonfinite['nan'])} field(s)")

    if nonfinite["inf"]:
        print(f"{RED}✗ FAIL: Found Inf values in {len(nonfinite['inf'])} field(s):{NC}")
        for field, info in nonfinite["inf"].items():
            print(f"  {field}: {info['count']} Inf values")
            if info["examples"]:
                for idx, val in info["examples"]:
                    print(f"    Halo {idx}: {field} = {val}")
        raise AssertionError(f"Inf values in {len(nonfinite['inf'])} field(s)")

    print(f"{GREEN}✓ PASS: No NaN or Inf values found{NC}")


def test_zero_values():
    """
    Check for zero values dynamically for ALL properties (warnings, not failures)
    Respects sentinels - suppresses warnings for properties where 0/0.0 is intentional
    """
    print()
    print("=" * 60)
    print("ZERO VALUE CHECKS (warnings, respects sentinels)")
    print("=" * 60)

    if not VALIDATION_MANIFEST_PATH.exists():
        raise TestSkipped("validation manifest not found: run 'make generate'")

    manifest = load_validation_manifest()

    if not MIMIC_EXE.exists():
        raise TestSkipped("Mimic not built")

    output_file = regenerate_output()
    halos, metadata = load_output_halos(output_file)
    total_halos = metadata["TotHalos"]

    zero_counts = check_zeros(halos, manifest)

    if zero_counts:
        print(f"{YELLOW}⚠ WARNING: Found zero values in {len(zero_counts)} field(s):{NC}")
        print(f"(Properties with sentinel 0/0.0 are not shown)")
        for field, info in zero_counts.items():
            print(f"  {field}: {info['count']} zero values out of {total_halos} total")
            for idx, val in info["examples"][:3]:  # Limit to 3 examples
                print(f"    Halo {idx}: {field} = {val}")
        # Warnings, not failures: the shared runner emits a WARN marker for this
        return f"{len(zero_counts)} field(s) with zero values"
    print(f"{GREEN}✓ No unexpected zero values found{NC}")


def test_physical_ranges():
    """
    Test that all OUTPUT properties are within ranges defined in metadata
    """
    print()
    print("=" * 60)
    print("PHYSICAL RANGE VALIDATION")
    print("=" * 60)

    if not VALIDATION_MANIFEST_PATH.exists():
        raise TestSkipped("validation manifest not found: run 'make generate'")

    manifest = load_validation_manifest()

    if not MIMIC_EXE.exists():
        raise TestSkipped("Mimic not built")

    output_file = regenerate_output()
    halos, metadata = load_output_halos(output_file)

    failures = 0

    props = manifest.get("properties", {})
    output_fields = list(halos.dtype.names)

    # Report summary
    with_ranges = [k for k, v in props.items() if "range" in v]
    print(f"Found {len(output_fields)} output fields in binary file.")
    print(f"Validation specs present for {len(with_ranges)} properties with ranges.\n")

    # Validate each field present in output and manifest
    for field in output_fields:
        spec = props.get(field)
        if not spec or "range" not in spec:
            # No spec, skip with notice
            print(f"{YELLOW}Skipping {field}: no range specified in metadata{NC}")
            continue

        rmin, rmax = spec["range"]
        sentinels = set(spec.get("sentinels", []))
        data = getattr(halos, field)

        # Build mask for values to check (exclude sentinels)
        if data.ndim == 1:
            mask = np.ones_like(data, dtype=bool)
            if len(sentinels) > 0:
                for s in sentinels:
                    mask &= data != s

            values = data[mask]

            below = np.sum(values < rmin)
            above = np.sum(values > rmax)
            total_checked = len(values)
            total_failed = below + above

            if total_failed > 0:
                failures += 1
                print(f"{RED}✗ FAIL: {field} outside [{rmin}, {rmax}] inclusive{NC}")
                print(f"  Actual range: {np.min(values):.4g} to {np.max(values):.4g}")
                print(
                    f"  Failed: {total_failed} out of {total_checked} halos ({100.0*total_failed/total_checked:.1f}%)"
                )
            else:
                print(f"{GREEN}✓ PASS: {field} within [{rmin}, {rmax}] (inclusive){NC}")

        else:
            # Vector field: check each component against same range
            # Note: sentinel handling for vectors is not applied unless exact scalar sentinels match per-component
            comp_fail = 0
            all_comp_values = []  # Track all component values for min/max reporting

            for ci in range(data.shape[1]):
                comp = data[:, ci]
                mask = np.ones_like(comp, dtype=bool)
                if len(sentinels) > 0:
                    for s in sentinels:
                        mask &= comp != s
                values = comp[mask]
                all_comp_values.extend(values)  # Collect values from all components

                below = np.sum(values < rmin)
                above = np.sum(values > rmax)
                if below > 0 or above > 0:
                    comp_fail += 1

            if comp_fail > 0:
                failures += 1
                all_vals = np.array(all_comp_values)
                # Count how many values failed across all components
                total_failed = np.sum((all_vals < rmin) | (all_vals > rmax))
                total_checked = len(all_vals)

                print(f"{RED}✗ FAIL: {field} component(s) outside [{rmin}, {rmax}] inclusive{NC}")
                print(
                    f"  Actual range: {np.min(all_vals):.4g} to {np.max(all_vals):.4g} (across all components)"
                )
                print(
                    f"  Failed: {total_failed} out of {total_checked} values ({100.0*total_failed/total_checked:.1f}%)"
                )
            else:
                print(f"{GREEN}✓ PASS: {field} components within [{rmin}, {rmax}] (inclusive){NC}")

    assert failures == 0, f"{failures} failure(s)"


def test_unit_consistency():
    """
    Test unit consistency and physical relationships

    Validates that related physical quantities have correct relationships,
    which catches unit conversion bugs (like incorrect G values).
    """
    print()
    print("=" * 60)
    print("UNIT CONSISTENCY CHECKS")
    print("=" * 60)

    if not MIMIC_EXE.exists():
        raise TestSkipped("Mimic not built")

    output_file = regenerate_output()
    halos, metadata = load_output_halos(output_file)
    schema = load_schema(output_file)

    failures = 0

    # Gravitational constant in active Mimic reference units.
    G_CODE = gravity_code_units_from_schema(schema)

    # Speed of light (km/s) - velocities must be << c
    C_LIGHT = 299792.458

    print("\n1. Virial relation consistency: Vvir^2 ≈ G*Mvir/Rvir")

    # Only check halos with valid virial properties
    valid_mask = (halos.Mvir > 0) & (halos.Rvir > 0) & (halos.Vvir > 0)
    valid_halos = np.sum(valid_mask)

    if valid_halos == 0:
        print(f"{YELLOW}⚠ WARNING: No halos with valid virial properties{NC}")
    else:
        # Calculate expected Vvir from Mvir and Rvir
        expected_vvir_sq = G_CODE * halos.Mvir[valid_mask] / halos.Rvir[valid_mask]
        actual_vvir_sq = halos.Vvir[valid_mask] ** 2

        # Allow 1% relative error (accounts for numerical precision)
        rel_error = np.abs((actual_vvir_sq - expected_vvir_sq) / expected_vvir_sq)
        bad_mask = rel_error > 0.01

        n_bad = np.sum(bad_mask)
        if n_bad > 0:
            failures += 1
            max_error = np.max(rel_error[bad_mask]) * 100
            print(f"{RED}✗ FAIL: {n_bad}/{valid_halos} halos violate virial relation{NC}")
            print(f"  Max relative error: {max_error:.2f}%")
            print(f"  Expected: Vvir^2 = G*Mvir/Rvir where G ≈ {G_CODE:.2f}")

            # Show examples
            bad_indices = np.where(valid_mask)[0][bad_mask][:3]
            for idx in bad_indices:
                expected = np.sqrt(G_CODE * halos.Mvir[idx] / halos.Rvir[idx])
                actual = halos.Vvir[idx]
                error = 100 * abs(actual - expected) / expected
                print(
                    f"  Halo {idx}: Vvir={actual:.2f} km/s, expected={expected:.2f} km/s (error: {error:.1f}%)"
                )
        else:
            max_error = np.max(rel_error) * 100 if len(rel_error) > 0 else 0
            print(
                f"{GREEN}✓ PASS: All {valid_halos} halos satisfy virial relation (max error: {max_error:.3f}%){NC}"
            )

    print("\n2. Velocity sanity: Vvir << speed of light")

    max_vvir = np.max(halos.Vvir)
    vvir_fraction = max_vvir / C_LIGHT

    if max_vvir > 0.01 * C_LIGHT:  # > 1% of c is suspicious
        failures += 1
        print(f"{RED}✗ FAIL: Velocities suspiciously large{NC}")
        print(f"  Max Vvir: {max_vvir:.1f} km/s ({vvir_fraction*100:.2f}% of c)")
        print(f"  This suggests unit conversion error")
    else:
        print(f"{GREEN}✓ PASS: Max Vvir = {max_vvir:.1f} km/s ({vvir_fraction*100:.4f}% of c){NC}")

    print("\n3. Mass positivity: metadata-selected mass fields >= 0")

    mass_failures = 0
    try:
        manifest = load_validation_manifest()
        mass_fields = mass_fields_from_metadata(manifest, halos.dtype.names)
    except Exception as e:
        print(f"{YELLOW}⚠ WARNING: Could not load mass-field metadata: {e}{NC}")
        manifest = {}
        mass_fields = []

    for field in mass_fields:
        data = getattr(halos, field)
        mask = np.ones_like(data, dtype=bool)
        for sentinel in manifest.get("properties", {}).get(field, {}).get("sentinels", []):
            mask &= data != sentinel
        values = data[mask]
        negative = np.sum(values < 0)
        if negative > 0:
            mass_failures += 1
            print(f"{RED}✗ FAIL: {field} has {negative} negative values{NC}")
            neg_indices = np.where(mask & (data < 0))[0][:3]
            for idx in neg_indices:
                print(f"  Halo {idx}: {field} = {data[idx]:.6e}")

    if mass_failures > 0:
        failures += 1
    elif not mass_fields:
        print(f"{YELLOW}⚠ No metadata-selected mass fields to check{NC}")
    else:
        print(
            f"{GREEN}✓ PASS: All {len(mass_fields)} metadata-selected mass fields are non-negative{NC}"
        )

    print("\n4. Time step sanity: dT reasonable")

    if hasattr(halos, "dT"):
        # dT is in Myr (output units after conversion)
        # Valid range: 0 to ~1000 Myr (1 Gyr) for typical timesteps
        # -1.0 is sentinel for "not set"
        valid_dt = halos.dT[(halos.dT >= 0) & (halos.dT != -1.0)]

        if len(valid_dt) > 0:
            max_dt = np.max(valid_dt)
            if max_dt > 2000:  # > 2 Gyr is suspicious
                failures += 1
                print(f"{RED}✗ FAIL: dT values suspiciously large{NC}")
                print(f"  Max dT: {max_dt:.1f} Myr")
                print(f"  Expected: < 1000 Myr for typical timesteps")
            else:
                print(f"{GREEN}✓ PASS: dT values reasonable (max: {max_dt:.1f} Myr){NC}")
        else:
            print(f"{YELLOW}⚠ No valid dT values to check{NC}")

    assert failures == 0, f"{failures} failure(s)"


def main():
    """Run this file's tests via the shared framework runner."""
    print(f"Repository root: {REPO_ROOT}")
    print(f"Mimic executable: {MIMIC_EXE}")

    return run_test_suite(
        [
            test_numerical_validity,
            test_zero_values,
            test_physical_ranges,
            test_unit_consistency,
        ],
        "Scientific Validation (test_scientific.py)",
    )


if __name__ == "__main__":
    sys.exit(main())
