/**
 * @file    python_example.c
 * @brief   Write a run-specific Python example script to the output directory.
 *
 * Generates example_Mvir_Len_plot.py alongside the output data. The script
 * is pre-configured for this run (format, filename, snapshot, cosmology) and
 * can be executed directly with no arguments.
 */

#include <stdio.h>
#include <string.h>

#include "config.h"
#include "globals.h"
#include "types.h"
#include "error.h"
#include "io.h"

/* Convenience macros for writing static Python lines and C-substituted lines. */
#define PY(s)        fputs(s "\n", fh)
#define PYF(fs, ...) fprintf(fh, fs "\n", __VA_ARGS__)

void write_python_example(const char *output_dir) {
  char path[MAX_STRING_LEN + 50];
  snprintf(path, sizeof(path), "%s/example_Mvir_Len_plot.py", output_dir);

  FILE *fh = fopen(path, "w");
  if (fh == NULL) {
    WARNING_LOG("Failed to write Python example: %s", path);
    return;
  }

  int         snap_num = (MimicConfig.NOUT > 0) ? MimicConfig.ListOutputSnaps[0] : 0;
  double      z        = MimicConfig.ZZ[snap_num];
  const char *fmt      = (MimicConfig.OutputFormat == output_hdf5) ? "hdf5" : "binary";
  int         is_hdf5  = (MimicConfig.OutputFormat == output_hdf5);

  /* ---- header / docstring ---- */
  PY("#!/usr/bin/env python");
  PYF("\"\"\"Reading Mimic output: %s  snapshot %d  (z = %.3f)", MimicConfig.ModelName, snap_num, z);
  PY("");
  PY("Generated by Mimic. Run directly from any directory:");
  PY("    python /path/to/output_dir/example_Mvir_Len_plot.py");
  PY("");
  PYF("Output format : %s", fmt);
  PYF("Output files  : %s.*  (in the same directory as this script)", MimicConfig.OutputFileBaseName);
  PYF("Snapshot      : %d  (z = %.3f)", snap_num, z);
  PY("");
  PY("Reads the most recent snapshot, prints every available output field,");
  PY("then plots virial mass vs halo particle count for a random sample.");
  PY("");
  if (is_hdf5) {
    PY("Requires: numpy  matplotlib  h5py");
  } else {
    PY("Requires: numpy  matplotlib");
  }
  PY("\"\"\"");
  PY("");
  if (!is_hdf5) {
    PY("import glob");
  }
  PY("import json");
  PY("import sys");
  PY("from pathlib import Path");
  PY("");
  PY("import numpy as np");
  PY("");

  /* ---- run-specific constants ---- */
  PY("# ---------------------------------------------------------------------------");
  PY("# Run configuration  (embedded by Mimic at generation time)");
  PY("# ---------------------------------------------------------------------------");
  PY("OUTPUT_DIR      = Path(__file__).parent   # data lives alongside this script");
  PYF("OUTPUT_FILENAME = \"%s\"                  # base name of output files", MimicConfig.OutputFileBaseName);
  PYF("SNAPSHOT_NUM    = %d                      # most recent output snapshot", snap_num);
  PYF("SNAPSHOT_Z      = %.3f                    # redshift of that snapshot", z);
  PYF("HUBBLE_H        = %f                      # for unit conversion (Msun/h -> Msun)", MimicConfig.Hubble_h);
  if (!is_hdf5) {
    const char *p      = strrchr(MimicConfig.FileWithSnapList, '/');
    const char *a_list = p ? p + 1 : MimicConfig.FileWithSnapList;
    PYF("A_LIST_FILE     = OUTPUT_DIR / \"metadata\" / \"%s\"  # snapshot redshift list", a_list);
  }
  PY("SAMPLE_SIZE     = 5000                    # max halos in the scatter plot");
  PY("");
  PY("");

  /* ---- schema ---- */
  PY("# ---------------------------------------------------------------------------");
  PY("# Schema");
  PY("# ---------------------------------------------------------------------------");
  PY("");
  PY("def load_schema():");
  PY("    \"\"\"Load the output schema that describes every field in this run.\"\"\"");
  PY("    path = OUTPUT_DIR / \"metadata\" / \"output_schema.json\"");
  PY("    if not path.exists():");
  PY("        sys.exit(f\"Schema not found: {path}\")");
  PY("    with path.open() as fh:");
  PY("        return json.load(fh)");
  PY("");
  PY("");
  PY("def print_schema(schema):");
  PY("    \"\"\"Print every output field with its numpy type, units, and description.\"\"\"");
  PY("    n = len(schema[\"fields\"])");
  PY("    print(f\"\\nFields in this output ({schema.get('model', '')}, {n} fields)\")");
  PY("    print(f\"  {'Field':<30} {'Type':<14} {'Units':<22} Description\")");
  PY("    print(\"  \" + \"-\" * 100)");
  PY("    for f in schema[\"fields\"]:");
  PY("        shape = f.get(\"shape\", [])");
  PY("        t = f[\"numpy_type\"] + (f\"[{','.join(str(s) for s in shape)}]\" if shape else \"\")");
  PY("        print(f\"  {f['name']:<30} {t:<14} {f.get('units', ''):<22} {f.get('description', '')}\")");
  PY("    print()");
  PY("");
  PY("");

  /* ---- reader: format-specific ---- */
  PY("# ---------------------------------------------------------------------------");
  PY("# Reader");
  PY("# ---------------------------------------------------------------------------");
  PY("");

  if (is_hdf5) {
    PY("def read_halos():");
    PY("    \"\"\"");
    PY("    Read HDF5 output for SNAPSHOT_NUM.");
    PY("");
    PY("    HDF5 layout (individual file):  Snap{NNN}/Galaxies");
    PY("    HDF5 layout (master file):      Snap{NNN}/File{NNN}/Galaxies");
    PY("    \"\"\"");
    PY("    try:");
    PY("        import h5py");
    PY("    except ImportError:");
    PY("        sys.exit(\"h5py required: pip install h5py\")");
    PY("");
    PY("    group = f\"Snap{SNAPSHOT_NUM:03d}\"");
    PY("");
    PY("    def from_file(hf):");
    PY("        snap = hf.get(group)");
    PY("        if snap is None:");
    PY("            return None");
    PY("        if \"Galaxies\" in snap:");
    PY("            return np.array(snap[\"Galaxies\"][:])");
    PY("        chunks = [np.array(snap[k][\"Galaxies\"][:])");
    PY("                  for k in sorted(snap.keys()) if k.startswith(\"File\") and \"Galaxies\" in snap[k]]");
    PY("        return np.concatenate(chunks) if chunks else None");
    PY("");
    PY("    master = OUTPUT_DIR / f\"{OUTPUT_FILENAME}.hdf5\"");
    PY("    if master.exists():");
    PY("        print(f\"  {master.name}\")");
    PY("        with h5py.File(master, \"r\") as hf:");
    PY("            data = from_file(hf)");
    PY("        if data is not None:");
    PY("            return data.view(np.recarray)");
    PY("");
    PY("    parts = []");
    PY("    for path in sorted(OUTPUT_DIR.glob(f\"{OUTPUT_FILENAME}_*.hdf5\")):");
    PY("        with h5py.File(path, \"r\") as hf:");
    PY("            chunk = from_file(hf)");
    PY("        if chunk is not None:");
    PY("            parts.append(chunk)");
    PY("            print(f\"  {path.name}: {len(chunk)} records\")");
    PY("    if not parts:");
    PY("        sys.exit(f\"No HDF5 data found for group '{group}'\")");
    PY("    return np.concatenate(parts).view(np.recarray)");
  } else {
    PY("def build_dtype(schema):");
    PY("    \"\"\"Build a numpy dtype from the schema's byte offsets and record size.\"\"\"");
    PY("    tm = {\"int32\": np.int32, \"int64\": np.int64, \"float32\": np.float32, \"float64\": np.float64}");
    PY("    names, formats, offsets = [], [], []");
    PY("    for f in schema[\"fields\"]:");
    PY("        shape = tuple(f.get(\"shape\", []))");
    PY("        dt = np.dtype((tm[f[\"numpy_type\"]], shape)) if shape else np.dtype(tm[f[\"numpy_type\"]])");
    PY("        names.append(f[\"name\"])");
    PY("        formats.append(dt)");
    PY("        offsets.append(f[\"offset\"])");
    PY("    return np.dtype({\"names\": names, \"formats\": formats, \"offsets\": offsets,");
    PY("                     \"itemsize\": schema[\"record\"][\"binary_record_size\"]})");
    PY("");
    PY("");
    PY("def read_halos(schema):");
    PY("    \"\"\"");
    PY("    Read all binary output files for SNAPSHOT_NUM.");
    PY("");
    PY("    Binary file layout:");
    PY("        int32          ntrees      number of merger trees");
    PY("        int32          ntotgals    total halo records");
    PY("        int32[ntrees]              per-tree halo count  (skipped)");
    PY("        HaloOutput[ntotgals]       packed records, dtype from schema");
    PY("");
    PY("    Files named:  <OUTPUT_FILENAME>_z<SNAPSHOT_Z>_<filenum>");
    PY("    e.g.          model_z0.000_0   model_z0.000_1   ...");
    PY("    \"\"\"");
    PY("    dtype   = build_dtype(schema)");
    PY("    pattern = str(OUTPUT_DIR / f\"{OUTPUT_FILENAME}_z{SNAPSHOT_Z:.3f}_*\")");
    PY("    files   = sorted(glob.glob(pattern))");
    PY("    if not files:");
    PY("        sys.exit(f\"No binary files found: {pattern}\")");
    PY("    parts = []");
    PY("    for path in files:");
    PY("        with open(path, \"rb\") as fh:");
    PY("            ntrees   = np.fromfile(fh, np.int32, 1)[0]");
    PY("            ntotgals = np.fromfile(fh, np.int32, 1)[0]");
    PY("            np.fromfile(fh, np.int32, ntrees)               # skip per-tree table");
    PY("            parts.append(np.fromfile(fh, dtype, ntotgals))");
    PY("        print(f\"  {Path(path).name}: {parts[-1].shape[0]} records\")");
    PY("    return np.concatenate(parts).view(np.recarray)");
  }

  PY("");
  PY("");

  /* ---- main ---- */
  PY("# ---------------------------------------------------------------------------");
  PY("# Main");
  PY("# ---------------------------------------------------------------------------");
  PY("");
  PY("def main():");
  PY("    schema = load_schema()");
  PY("    print_schema(schema)");
  PY("");
  PY("    print(f\"Reading snapshot {SNAPSHOT_NUM} (z = {SNAPSHOT_Z:.3f}) from {OUTPUT_DIR} ...\")");
  if (is_hdf5) {
    PY("    halos = read_halos()");
  } else {
    PY("    halos = read_halos(schema)");
  }
  PY("    print(f\"\\nLoaded {len(halos):,} records.\")");
  PY("");
  PY("    # Type 0 = FOF central;  Type 1 = satellite;  Type 2 = orphan");
  PY("    mask = (halos.Type == 0) & (halos.Mvir > 0.0) & (halos.Len > 0)");
  PY("    centrals = halos[mask]");
  PY("    print(f\"Centrals with Mvir > 0 and Len > 0: {len(centrals):,}\")");
  PY("    if not len(centrals):");
  PY("        sys.exit(\"No halos pass the filter.\")");
  PY("");
  PY("    n = min(SAMPLE_SIZE, len(centrals))");
  PY("    idx = np.random.default_rng(42).choice(len(centrals), size=n, replace=False)");
  PY("    sample = centrals[idx]");
  PY("");
  PY("    # Mvir: 1e10 Msun/h -> divide by HUBBLE_H to get Msun");
  PY("    # Len: particle count (dimensionless integer)");
  PY("    log_mvir = np.log10(sample.Mvir * 1.0e10 / HUBBLE_H)");
  PY("    log_len  = np.log10(sample.Len.astype(float))");
  PY("");
  PY("    import matplotlib");
  PY("    matplotlib.use(\"Agg\")  # remove this line for an interactive window");
  PY("    import matplotlib.pyplot as plt");
  PY("");
  PY("    plt.rc(\"xtick\", labelsize=\"x-large\")");
  PY("    plt.rc(\"ytick\", labelsize=\"x-large\")");
  PY("");
  PY("    fig, ax = plt.subplots(figsize=(8, 6))");
  PY("    ax.scatter(log_mvir, log_len, s=4, alpha=0.45, linewidths=0, color=\"steelblue\",");
  PY("               label=f\"Central halos  (n = {n:,})\")");
  PY("    ax.set_xlabel(\"log10(Mvir / Msun)\", fontsize=14)");
  PY("    ax.set_ylabel(\"log10(Len / particles)\", fontsize=14)");
  PY("    ax.set_title(");
  PY("        f\"Snapshot {SNAPSHOT_NUM}  z={SNAPSHOT_Z:.3f}  --  {OUTPUT_FILENAME}\",");
  PY("        fontsize=12)");
  PY("    ax.legend(fontsize=12, framealpha=0.7)");
  PY("    fig.tight_layout()");
  PY("");
  PY("    out_path = OUTPUT_DIR / \"example_Mvir_Len.png\"");
  PY("    fig.savefig(out_path, dpi=150)");
  PY("    plt.close(fig)");
  PY("    print(f\"\\nPlot saved: {out_path}\")");
  PY("");
  PY("");
  PY("if __name__ == \"__main__\":");
  PY("    main()");

  fclose(fh);
  INFO_LOG("Python example written to %s/example_Mvir_Len_plot.py", output_dir);
}

#undef PY
#undef PYF
