"""AUTO-GENERATED CODE - DO NOT EDIT

Generated by: scripts/generate_properties.py
Generated on: 2025-11-08 11:40:02

Source files:
  - metadata/properties/halo_properties.yaml
  - metadata/properties/galaxy_properties.yaml

Source MD5: 4a773f399ed870b51ef154be8f439360
To regenerate: make generate
"""

import numpy as np

def get_binary_dtype():
    """Return NumPy dtype for binary output format (with struct alignment)."""
    return np.dtype([
        ("SnapNum", np.int32),
        ("Type", np.int32),
        ("HaloIndex", np.int64),
        ("CentralHaloIndex", np.int64),
        ("MimicHaloIndex", np.int32),
        ("MimicTreeIndex", np.int32),
        ("SimulationHaloIndex", np.int64),
        ("MergeStatus", np.int32),
        ("mergeIntoID", np.int32),
        ("mergeIntoSnapNum", np.int32),
        ("dT", np.float32),
        ("Pos", (np.float32, 3)),
        ("Vel", (np.float32, 3)),
        ("Spin", (np.float32, 3)),
        ("Len", np.int32),
        ("Mvir", np.float32),
        ("CentralMvir", np.float32),
        ("Rvir", np.float32),
        ("Vvir", np.float32),
        ("Vmax", np.float32),
        ("VelDisp", np.float32),
        ("infallMvir", np.float32),
        ("infallVvir", np.float32),
        ("infallVmax", np.float32),
    ], align=True)

def get_hdf5_dtype():
    """Return NumPy dtype for HDF5 output format (no alignment)."""
    return np.dtype([
        ("SnapNum", np.int32),
        ("Type", np.int32),
        ("HaloIndex", np.int64),
        ("CentralHaloIndex", np.int64),
        ("MimicHaloIndex", np.int32),
        ("MimicTreeIndex", np.int32),
        ("SimulationHaloIndex", np.int64),
        ("MergeStatus", np.int32),
        ("mergeIntoID", np.int32),
        ("mergeIntoSnapNum", np.int32),
        ("dT", np.float32),
        ("Pos", (np.float32, 3)),
        ("Vel", (np.float32, 3)),
        ("Spin", (np.float32, 3)),
        ("Len", np.int32),
        ("Mvir", np.float32),
        ("CentralMvir", np.float32),
        ("Rvir", np.float32),
        ("Vvir", np.float32),
        ("Vmax", np.float32),
        ("VelDisp", np.float32),
        ("infallMvir", np.float32),
        ("infallVvir", np.float32),
        ("infallVmax", np.float32),
    ])
