#!/bin/bash
###############################################################################
# convert_worked_graph.sh - Convert the worked_graph L-Halo source into a
# version 3 test fixture for one L-Halo-sourced horizontal package
#
# The worked_graph source (trees_worked_graph.0 beside this script, written by
# generate_sources.py) is one synthetic five-halo forest over five snapshots
# with gapped links, a FoF satellite and an empty snapshot. Its record layout
# is the shipped L-Halo record and nothing in it depends on a simulation, so
# every horizontal package converted from L-Halo binary can carry its own copy
# of it. This script converts it with convert/mimic-convert/convert_trees.py
# (ingest, transpose, write, then report, which runs the producer validation
# battery) under the SOURCE package's own simulation_info.yaml, converter
# profile and halo_properties.yaml, against a scale-factor list made of the
# last five entries of that package's a_list, so the fixture's headers carry
# exactly the cosmology, box size, particle mass and scale factors the
# horizontal package declares and its reader checks at open. The written
# dataset and the fixture a_list are installed under
# simulations/<horizontal package>/_tests/data/worked_graph/, overwriting the
# files of the same names. The converter is the only producer: nothing here
# edits a written file. The source itself is regenerated by
# ../regenerate.sh, not here.
#
# Usage (from anywhere; called by each package's _tests/data/regenerate.sh):
#   convert_worked_graph.sh <horizontal package> <source package> <a_list file>
#   e.g. convert_worked_graph.sh millennium-horizontal millennium millennium.a_list
#
# Exit codes: 0 on success; non-zero if an argument is wrong or any converter
# stage fails.
###############################################################################

set -euo pipefail

if [ "$#" -ne 3 ]; then
    echo "usage: $0 <horizontal package> <source package> <a_list file>" >&2
    exit 2
fi
PACKAGE="$1"
SOURCE_PACKAGE="$2"
A_LIST_NAME="$3"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../../.." && pwd)"
cd "$REPO_ROOT"

# Resolved from REPO_ROOT at run time, so shellcheck cannot follow it without -x.
# shellcheck source=scripts/lib/python.sh disable=SC1091
. "${REPO_ROOT}/scripts/lib/python.sh"

SOURCE_DIR="simulations/mini-millennium-horizontal/_tests/data/source"
S="simulations/${SOURCE_PACKAGE}"
FIXTURE_DIR="simulations/${PACKAGE}/_tests/data/worked_graph"
CONVERT="convert/mimic-convert/convert_trees.py"
FIXTURE_SNAPSHOTS=5

for required in "${SOURCE_DIR}/trees_worked_graph.0" "${S}/simulation_info.yaml" \
    "${S}/converter_columns.yaml" "${S}/halo_properties.yaml" "${S}/${A_LIST_NAME}"; do
    if [ ! -f "$required" ]; then
        echo "ERROR: required input not found: ${required}" >&2
        exit 1
    fi
done

WORKROOT="$(mktemp -d "${TMPDIR:-/tmp}/mimic_worked_graph_${PACKAGE}.XXXXXX")"
trap 'rm -rf "$WORKROOT"' EXIT
workdir="${WORKROOT}/worked_graph"
a_list="${WORKROOT}/worked_graph.a_list"

# The last five scale factors of the package's own list, renumbered from 0 by
# position, exactly as the mini-Millennium fixtures take theirs.
grep -v '^[[:space:]]*\(#\|$\)' "${S}/${A_LIST_NAME}" | tail -n "$FIXTURE_SNAPSHOTS" > "$a_list"

"$MIMIC_PYTHON" "$CONVERT" ingest --workdir "$workdir" --source-format lhalo_binary \
    --simulation-info "${S}/simulation_info.yaml" --a-list "$a_list" \
    --column-map "${S}/converter_columns.yaml" --source-dir "$SOURCE_DIR" \
    --tree-name trees_worked_graph --halo-properties "${S}/halo_properties.yaml" \
    --first-file 0 --last-file 0
"$MIMIC_PYTHON" "$CONVERT" transpose --workdir "$workdir"
"$MIMIC_PYTHON" "$CONVERT" write --workdir "$workdir" --simulation-info "${S}/simulation_info.yaml"
"$MIMIC_PYTHON" "$CONVERT" report --workdir "$workdir"

mkdir -p "$FIXTURE_DIR"
cp "$workdir"/write/attempt_*/snapshot_*.h5 "$workdir"/write/attempt_*/forests.h5 "$FIXTURE_DIR"/
cp "$a_list" "$FIXTURE_DIR"/worked_graph.a_list
echo "Installed the worked_graph fixture under ${FIXTURE_DIR}"
