#!/usr/bin/env python3
"""
Module Registry Generator for Mimic

Generates module registration code and test configurations from module_info.yaml
metadata files. This eliminates manual synchronization and implements the
metadata-driven module architecture.

Usage:
    python3 scripts/generate_module_registry.py [--dry-run] [--verbose]

Reads:
    src/modules/*/module_info.yaml

Generates:
    src/modules/_system/generated/module_init.c    - Module registration code
    tests/generated/module_sources.mk              - Test build configuration
    build/module_registry_hash.txt                 - Validation hash

Exit codes:
    0 - Success
    1 - Generation failed (validation errors, I/O errors)

Author: Module Metadata System (Phase 4.2.5)
Date: 2025-11-12
"""

import argparse
import hashlib
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install PyYAML", file=sys.stderr)
    sys.exit(1)

# ==============================================================================
# COLOR OUTPUT
# ==============================================================================

# ANSI color codes (disabled if not a TTY)
if sys.stdout.isatty():
    COLOR_RED = "\033[91m"
    COLOR_YELLOW = "\033[93m"
    COLOR_RESET = "\033[0m"
else:
    COLOR_RED = ""
    COLOR_YELLOW = ""
    COLOR_RESET = ""


def print_error(msg: str) -> None:
    """Print error message in red."""
    print(f"{COLOR_RED}ERROR: {msg}{COLOR_RESET}", file=sys.stderr)


def print_warning(msg: str) -> None:
    """Print warning message in yellow."""
    print(f"{COLOR_YELLOW}WARNING: {msg}{COLOR_RESET}")


# ==============================================================================
# PATHS
# ==============================================================================

# Repository root (parent of scripts/)
REPO_ROOT = Path(__file__).parent.parent

# Module directory
MODULES_DIR = REPO_ROOT / "src" / "modules"

# Output files
MODULE_INIT_C = (
    REPO_ROOT / "src" / "modules" / "_system" / "generated" / "module_init.c"
)
MODULE_SOURCES_MK = REPO_ROOT / "tests" / "generated" / "module_sources.mk"
MODULE_HASH_FILE = REPO_ROOT / "build" / "module_registry_hash.txt"

# ==============================================================================
# HEADER GENERATION (consistent across all generators)
# ==============================================================================


def generate_c_header(metadata_hash: str, description: str = "") -> str:
    """Generate consistent C header for all generated files."""
    header = "/* AUTO-GENERATED CODE - DO NOT EDIT\n"
    header += " *\n"
    header += " * Generated by: scripts/generate_module_registry.py\n"
    header += " *\n"
    header += " * Source: src/modules/ * /module_info.yaml\n"
    if description:
        header += " *\n"
        for line in description.split("\n"):
            header += f" * {line}\n" if line else " *\n"
    header += " *\n"
    header += f" * Source MD5: {metadata_hash}\n"
    header += " * To regenerate: make generate\n"
    header += " */\n"
    return header


def generate_makefile_header(metadata_hash: str) -> str:
    """Generate consistent Makefile header for all generated files."""
    header = "# AUTO-GENERATED CODE - DO NOT EDIT\n"
    header += "#\n"
    header += "# Generated by: scripts/generate_module_registry.py\n"
    header += "#\n"
    header += "# Source: src/modules/*/module_info.yaml\n"
    header += "#\n"
    header += f"# Source MD5: {metadata_hash}\n"
    header += "# To regenerate: make generate\n"
    return header


# ==============================================================================
# MODULE DISCOVERY
# ==============================================================================


def load_module_metadata(module_dir: Path) -> Optional[Dict[str, Any]]:
    """Load module_info.yaml from module directory."""
    yaml_path = module_dir / "module_info.yaml"

    if not yaml_path.exists():
        return None

    try:
        with open(yaml_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
            if data is None:
                return None
            module = data.get("module", None)
            if module:
                # Add module directory path for reference
                module["_module_dir"] = module_dir
                module["_pattern"] = "directory"

                # Build sources list
                # {name}.c is always implicit, only additional files need declaration
                name = module["name"]
                sources = [f"{name}.c"]

                if "additional_files" in module:
                    # Add any additional .c files
                    additional = module["additional_files"]
                    sources.extend([f for f in additional if f.endswith(".c")])

                module["sources"] = sources

            return module
    except yaml.YAMLError as e:
        print(f"ERROR: Failed to parse {yaml_path}: {e}", file=sys.stderr)
        return None


def create_standalone_module_metadata(module_name: str, c_file: Path) -> Dict[str, Any]:
    """Create minimal metadata for standalone .c file module."""
    return {
        "name": module_name,
        "display_name": module_name.replace("_", " ").title(),
        "version": "1.0.0",
        "author": "Auto-generated",
        "sources": [f"{module_name}.c"],
        "supported_processing_modes": ["process_full_halo", "process_by_galaxy"],
        "dependencies": {"properties": [], "parameters": []},
        "_module_dir": c_file.parent,
        "_pattern": "standalone",
        "_standalone_file": c_file,
    }


def discover_modules() -> List[Dict[str, Any]]:
    """Discover all modules (directories with module_info.yaml OR standalone .c files)."""
    modules = []

    if not MODULES_DIR.exists():
        print(f"ERROR: Module directory not found: {MODULES_DIR}", file=sys.stderr)
        return []

    for item in sorted(MODULES_DIR.iterdir()):
        # Skip items starting with underscore (except _system)
        if item.name.startswith("_") and item.name != "_system":
            continue

        # Pattern 1: Directory with module_info.yaml
        if item.is_dir():
            # Handle _system directory specially - only include test_fixture
            if item.name == "_system":
                test_fixture_dir = item / "test_fixture"
                if test_fixture_dir.exists() and test_fixture_dir.is_dir():
                    metadata = load_module_metadata(test_fixture_dir)
                    if metadata:
                        modules.append(metadata)
                continue

            # Regular module directory
            metadata = load_module_metadata(item)
            if metadata:
                modules.append(metadata)

        # Pattern 2: Standalone .c file
        elif item.is_file() and item.suffix == ".c":
            module_name = item.stem
            metadata = create_standalone_module_metadata(module_name, item)
            modules.append(metadata)
            print(f"  Discovered standalone module: {module_name}")

    return modules


# ==============================================================================
# DEPENDENCY RESOLUTION
# ==============================================================================


def resolve_dependencies(
    modules: List[Dict[str, Any]],
) -> Optional[List[Dict[str, Any]]]:
    """Return modules in order (no automatic dependency resolution).

    Note: Modules must be listed in correct execution order in the
    input YAML configuration file. No topological sorting is performed.
    """
    return modules if modules else []


# ==============================================================================
# VALIDATION
# ==============================================================================


def load_valid_properties() -> set:
    """Load all valid property names from halo and galaxy property files."""
    valid_properties = set()

    # Load galaxy properties
    galaxy_props_path = MODULES_DIR / "model_properties.yaml"
    if galaxy_props_path.exists():
        try:
            with open(galaxy_props_path, "r", encoding="utf-8") as f:
                props_yaml = yaml.safe_load(f)
            for prop in props_yaml.get("galaxy_properties", []):
                valid_properties.add(prop["name"])
        except (OSError, yaml.YAMLError, KeyError, TypeError) as e:
            print_warning(f"Failed to load galaxy properties: {e}")

    # Load halo properties
    halo_props_path = REPO_ROOT / "src" / "core" / "halo_properties.yaml"
    if halo_props_path.exists():
        try:
            with open(halo_props_path, "r", encoding="utf-8") as f:
                halo_yaml = yaml.safe_load(f)
            for prop in halo_yaml.get("halo_properties", []):
                valid_properties.add(prop["name"])
        except (OSError, yaml.YAMLError, KeyError, TypeError) as e:
            print_warning(f"Failed to load halo properties: {e}")

    return valid_properties


def validate_property_dependencies(
    modules: List[Dict[str, Any]], valid_properties: set
) -> List[str]:
    """
    Verify all module property dependencies exist in property metadata.

    Standalone modules skip property validation (minimal metadata).

    Returns list of error messages (empty if all valid).
    """
    errors = []

    for module in modules:
        module_name = module["name"]
        pattern = module.get("_pattern", "directory")

        # Skip validation for standalone modules (no metadata)
        if pattern == "standalone":
            continue

        declared_props = module.get("dependencies", {}).get("properties", [])

        for prop in declared_props:
            if prop not in valid_properties:
                errors.append(
                    f"{module_name}/module_info.yaml: Unknown property '{prop}' "
                    f"in dependencies.properties"
                )

    return errors


def validate_module_files(modules: List[Dict[str, Any]]) -> List[str]:
    """
    Verify all declared source files exist.

    Supports both new 'files' field and legacy 'sources' field.
    Standalone modules are automatically validated during discovery.

    Returns list of error messages (empty if all valid).
    """
    errors = []

    for module in modules:
        module_name = module["name"]
        module_dir = module.get("_module_dir")
        pattern = module.get("_pattern", "directory")

        if not module_dir:
            continue

        # Standalone modules already validated during discovery
        if pattern == "standalone":
            continue

        # Check source files (required)
        for source in module.get("sources", []):
            source_path = module_dir / source
            if not source_path.exists():
                errors.append(
                    f"{module_name}/module_info.yaml: Source file '{source}' not found\n"
                    f"    Expected at: {source_path}"
                )

    return errors


def validate_test_files(modules: List[Dict[str, Any]]) -> List[str]:
    """
    Check that declared test files exist.

    Returns list of warning messages (not errors - tests may be planned).
    """
    warnings = []
    valid_test_types = {"unit", "integration", "scientific"}

    for module in modules:
        module_name = module["name"]
        module_dir = module.get("_module_dir")

        if not module_dir:
            continue

        tests = module.get("tests", {})

        for test_type, test_path in tests.items():
            # Validate test type key
            if test_type not in valid_test_types:
                warnings.append(
                    f"{module_name}: Unknown test type '{test_type}' "
                    f"(expected: {', '.join(sorted(valid_test_types))})"
                )
                continue

            if not test_path:
                continue

            full_path = module_dir / test_path
            if not full_path.exists():
                warnings.append(
                    f"{module_name}: Declared {test_type} test not found: {test_path}"
                )

    return warnings


# ==============================================================================
# HASH COMPUTATION
# ==============================================================================


def compute_metadata_hash(modules: List[Dict[str, Any]]) -> str:
    """Compute MD5 hash of module metadata plus standalone module identities."""
    md5 = hashlib.md5()

    # Sort by module name for consistent ordering
    sorted_modules = sorted(modules, key=lambda m: m["name"])

    for module in sorted_modules:
        pattern = module.get("_pattern", "directory")
        if pattern == "standalone":
            standalone_file = module.get("_standalone_file")
            if standalone_file:
                relative_path = str(Path(standalone_file).relative_to(REPO_ROOT))
                md5.update(f"standalone:{module['name']}:{relative_path}".encode("utf-8"))
            continue

        module_dir = module.get("_module_dir")
        if module_dir:
            yaml_path = module_dir / "module_info.yaml"
            if yaml_path.exists():
                with open(yaml_path, "rb") as f:
                    md5.update(f.read())

    return md5.hexdigest()


def load_saved_hash() -> str:
    """Load the previously saved module metadata hash.

    Returns:
        The saved hash, or empty string if not found.
    """
    if MODULE_HASH_FILE.exists():
        try:
            with open(MODULE_HASH_FILE, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("MODULE_HASH="):
                        return line.split("=", 1)[1].strip()
        except Exception:
            pass
    return ""


# ==============================================================================
# CODE GENERATION - module_init.c
# ==============================================================================


def generate_lifecycle_forward_declarations(modules: List[Dict[str, Any]]) -> List[str]:
    """Generate forward declarations for module lifecycle functions."""
    lines = []
    lines.append(
        "/* ========================================================================== */"
    )
    lines.append(
        "/* FORWARD DECLARATIONS FOR MODULE LIFECYCLE FUNCTIONS                       */"
    )
    lines.append(
        "/* ========================================================================== */"
    )
    lines.append("")
    lines.append("/*")
    lines.append(" * Forward declarations for module lifecycle functions.")
    lines.append(" * These functions are implemented in each module's .c file.")
    lines.append(" *")
    lines.append(" * Eliminates need for per-module header files.")
    lines.append(" */")
    lines.append("")

    for module in sorted(modules, key=lambda m: m["name"]):
        name = module["name"]
        lines.append(f"extern int {name}_init(void);")
        lines.append(
            f"extern int {name}_process(struct ModuleContext *ctx, struct Halo *halos, int ngal);"
        )
        lines.append(f"extern int {name}_cleanup(void);")
        lines.append("")

    return lines


def generate_module_struct_definitions(modules: List[Dict[str, Any]]) -> List[str]:
    """Generate static struct Module definitions for all modules."""
    lines = []
    lines.append(
        "/* ========================================================================== */"
    )
    lines.append(
        "/* MODULE STRUCT DEFINITIONS (auto-generated from module_info.yaml)           */"
    )
    lines.append(
        "/* ========================================================================== */"
    )
    lines.append("")
    lines.append("/*")
    lines.append(" * Module struct definitions generated from module_info.yaml.")
    lines.append(
        " * Each module struct connects lifecycle functions to the module registry."
    )
    lines.append(" *")
    lines.append(" * Single source of truth: module_info.yaml")
    lines.append(" */")
    lines.append("")

    for module in sorted(modules, key=lambda m: m["name"]):
        name = module["name"]
        modes = module.get(
            "supported_processing_modes", ["process_full_halo", "process_by_galaxy"]
        )
        num_modes = len(modes)

        lines.append(f"static struct Module {name}_module = {{")
        lines.append(f'    .name = "{name}",')
        lines.append(f"    .init = {name}_init,")
        lines.append(f"    .process = {name}_process,")
        lines.append(f"    .cleanup = {name}_cleanup,")
        lines.append(f"    .supported_processing_modes = {name}_supported_modes,")
        lines.append(f"    .num_supported_modes = {num_modes}")
        lines.append("};")
        lines.append("")

    return lines


def generate_module_init_c(
    modules: List[Dict[str, Any]],
    metadata_hash: str,
    output_path: Path,
    dry_run: bool = False,
) -> bool:
    """Generate module registration code."""

    # Filter out utilities (is_utility: true) - they're test-only, not runtime modules
    runtime_modules = [m for m in modules if not m.get("is_utility", False)]

    lines = []

    # Header
    description = """To validate:
  make validate-modules"""
    header = generate_c_header(metadata_hash, description)
    lines.extend(header.splitlines())
    lines.append("")

    # Includes
    lines.append('#include "module_registry.h"')
    lines.append('#include "module_interface.h"')
    lines.append("")

    # Forward declarations for module lifecycle functions
    lines.extend(generate_lifecycle_forward_declarations(runtime_modules))

    # Generate processing mode arrays for each module
    lines.append(
        "/* ========================================================================== */"
    )
    lines.append(
        "/* SUPPORTED PROCESSING MODES (Auto-generated from module_info.yaml)         */"
    )
    lines.append(
        "/* ========================================================================== */"
    )
    lines.append("")
    lines.append("/*")
    lines.append(" * These arrays define which processing modes each module supports:")
    lines.append(
        " * - PROCESSING_MODE_FULL_HALO: Module processes full halo array (ngal > 1)"
    )
    lines.append(
        " * - PROCESSING_MODE_BY_GALAXY: Module processes one galaxy at a time (ngal = 1)"
    )
    lines.append(" *")
    lines.append(
        " * Generated from 'supported_processing_modes' field in module_info.yaml."
    )
    lines.append(
        " * If omitted, defaults to supporting both modes [process_full_halo, process_by_galaxy]."
    )
    lines.append(" *")
    lines.append(
        " * Modules reference these arrays in their Module struct initialization."
    )
    lines.append(" */")
    lines.append("")

    for module in sorted(runtime_modules, key=lambda m: m["name"]):
        name = module["name"]
        # Get supported modes from metadata (default to both if not specified)
        modes = module.get(
            "supported_processing_modes", ["process_full_halo", "process_by_galaxy"]
        )

        # Convert mode strings to enum values
        mode_enums = []
        for mode in modes:
            if mode == "process_full_halo":
                mode_enums.append("PROCESSING_MODE_FULL_HALO")
            elif mode == "process_by_galaxy":
                mode_enums.append("PROCESSING_MODE_BY_GALAXY")

        # Generate array
        mode_list = ", ".join(mode_enums)
        lines.append(
            f"const enum ProcessingMode {name}_supported_modes[] = {{{mode_list}}};"
        )

    lines.append("")

    # Module struct definitions
    lines.extend(generate_module_struct_definitions(runtime_modules))

    # Registration function
    lines.append(
        "/* ========================================================================== */"
    )
    lines.append(
        "/* MODULE REGISTRATION                                                        */"
    )
    lines.append(
        "/* ========================================================================== */"
    )
    lines.append("")
    lines.append("/**")
    lines.append(" * @brief Register all available physics modules")
    lines.append(" *")
    lines.append(f" * Modules registered: {len(runtime_modules)}")
    lines.append(" *")
    if runtime_modules:
        lines.append(" * Execution order (from config):")
        for i, module in enumerate(runtime_modules, 1):
            name = module["name"]
            properties = module.get("dependencies", {}).get("properties", [])

            if properties:
                props_str = ", ".join(properties)
                lines.append(f" * {i}. {name}: uses [{props_str}]")
            else:
                lines.append(f" * {i}. {name}: (no properties)")
    lines.append(" */")
    lines.append("void register_all_modules(void) {")

    if runtime_modules:
        lines.append(
            "    /* Directly register module structs (no per-module functions) */"
        )
        for module in runtime_modules:
            name = module["name"]
            properties = module.get("dependencies", {}).get("properties", [])

            # Add inline comment
            if properties:
                comment = f"  /* Uses: {', '.join(properties)} */"
            else:
                comment = ""

            lines.append(f"    module_registry_add(&{name}_module);{comment}")
    else:
        lines.append("    /* No modules to register */")

    lines.append("}")
    lines.append("")

    # Write file
    content = "\n".join(lines)

    if dry_run:
        print("=== module_init.c (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================


# ==============================================================================
# CODE GENERATION - module_sources.mk
# ==============================================================================


def generate_module_sources_mk(
    modules: List[Dict[str, Any]],
    metadata_hash: str,
    output_path: Path,
    dry_run: bool = False,
) -> bool:
    """Generate makefile fragment for test system."""

    # Filter out utilities (is_utility: true) - they have no runtime source files
    runtime_modules = [m for m in modules if not m.get("is_utility", False)]

    lines = []

    # Header
    header = generate_makefile_header(metadata_hash)
    lines.extend(header.splitlines())
    lines.append("")

    # Module source files
    lines.append("# Module source files for unit testing")
    lines.append("MODULE_SRCS = \\")
    lines.append("    $(SRC_DIR)/core/module_registry.c \\")

    # Add each module's source files
    for module in runtime_modules:
        module_dir = module.get("_module_dir")
        if module_dir:
            rel_path = module_dir.relative_to(REPO_ROOT / "src")
            sources = module.get("sources", [])
            for source in sources:
                lines.append(f"    $(SRC_DIR)/{rel_path}/{source} \\")

    # Add module_init.c last (no backslash)
    lines.append("    $(SRC_DIR)/modules/_system/generated/module_init.c")
    lines.append("")

    # Write file
    content = "\n".join(lines)

    if dry_run:
        print("\n=== module_sources.mk (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================
# CODE GENERATION - Hash File
# ==============================================================================


def generate_hash_file(
    metadata_hash: str, output_path: Path, dry_run: bool = False
) -> bool:
    """Generate hash file for validation."""

    lines = []
    lines.append("# AUTO-GENERATED CODE - DO NOT EDIT")
    lines.append("#")
    lines.append("# Hash of all module metadata files for validation")
    lines.append("#")
    lines.append(f"# Source MD5: {metadata_hash}")
    lines.append("# To regenerate: make generate")
    lines.append("")
    lines.append(f"MODULE_HASH={metadata_hash}")
    lines.append("")

    content = "\n".join(lines)

    if dry_run:
        print("\n=== module_registry_hash.txt (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================
# MAIN
# ==============================================================================


def main():
    """Main entry point."""

    parser = argparse.ArgumentParser(description="Generate module registration code")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated code without writing files",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()

    print("=" * 70)
    print("Module Registry Generation")
    print("=" * 70)
    print()

    # Discover modules
    modules = discover_modules()

    if not modules:
        print("WARNING: No modules found with module_info.yaml files")
        print("         Empty registration code will be generated")
        # Continue with empty list to generate valid (but empty) code

    if modules:
        # Count patterns
        directory_modules = [m for m in modules if m.get("_pattern") == "directory"]
        standalone_modules = [m for m in modules if m.get("_pattern") == "standalone"]

        print(f"Found {len(modules)} module(s):")
        if directory_modules:
            print(f"  Directory modules ({len(directory_modules)}):")
            for module in directory_modules:
                print(f"    - {module['name']} ({module.get('version', '1.0.0')})")
        if standalone_modules:
            print(f"  Standalone modules ({len(standalone_modules)}):")
            for module in standalone_modules:
                print(f"    - {module['name']} (standalone .c file)")
        print()

    # Resolve dependencies
    if modules:
        print("Resolving dependencies...")
        sorted_modules = resolve_dependencies(modules)
        if sorted_modules is None:
            print("ERROR: Dependency resolution failed", file=sys.stderr)
            return 1

        if args.verbose:
            print("Dependency order:")
            for i, module in enumerate(sorted_modules, 1):
                print(f"  {i}. {module['name']}")
        print()
    else:
        sorted_modules = []

    # ==========================================================================
    # VALIDATION
    # ==========================================================================

    if modules:
        # Validate module source/header files exist
        print("Validating module files...")
        file_errors = validate_module_files(modules)
        if file_errors:
            print_error("Missing module files:")
            for err in file_errors:
                print(f"  - {err}", file=sys.stderr)
            return 1
        print(f"✓ All module files exist")

        # Validate property dependencies
        print("Validating property dependencies...")
        valid_properties = load_valid_properties()
        if not valid_properties:
            print_warning("No valid properties loaded - skipping property validation")
        else:
            prop_errors = validate_property_dependencies(modules, valid_properties)
            if prop_errors:
                print_error("Invalid property dependencies:")
                for err in prop_errors:
                    print(f"  - {err}", file=sys.stderr)
                return 1
            print(
                f"✓ All property dependencies valid ({len(valid_properties)} properties available)"
            )

        # Check test files (warning only - always shown, not just verbose)
        print("Checking declared test files...")
        test_warnings = validate_test_files(modules)
        if test_warnings:
            print_warning("Some declared tests not found:")
            for warn in test_warnings:
                print(f"  {COLOR_YELLOW}- {warn}{COLOR_RESET}")
            print(
                f"  {COLOR_YELLOW}(Tests may be planned but not yet implemented){COLOR_RESET}"
            )
        else:
            print("✓ All declared test files exist")

        print()

    # Compute metadata hash
    metadata_hash = compute_metadata_hash(modules)
    if args.verbose:
        print(f"Metadata hash: {metadata_hash}")
        print()

    # Check if regeneration is needed (skip in dry-run mode)
    if not args.dry_run:
        saved_hash = load_saved_hash()
        if saved_hash == metadata_hash:
            print("✓ Module metadata unchanged - skipping regeneration")
            print(f"  Hash: {metadata_hash}")
            print()
            print("=" * 70)
            print("✓ SKIPPED (no changes)")
            print("=" * 70)
            return 0

        # Hash mismatch or missing - regeneration needed
        if saved_hash:
            print(f"Module metadata changed - regenerating...")
            print(f"  Old hash: {saved_hash}")
            print(f"  New hash: {metadata_hash}")
        else:
            print("No previous hash found - generating for first time...")
            print(f"  Hash: {metadata_hash}")
        print()

    # Generate files
    print("Generating files...")

    success = True
    success &= generate_module_init_c(
        sorted_modules, metadata_hash, MODULE_INIT_C, args.dry_run
    )
    success &= generate_module_sources_mk(
        sorted_modules, metadata_hash, MODULE_SOURCES_MK, args.dry_run
    )
    success &= generate_hash_file(metadata_hash, MODULE_HASH_FILE, args.dry_run)

    print()
    print("=" * 70)
    if success:
        if args.dry_run:
            print("✓ DRY RUN COMPLETED")
        else:
            print("✓ GENERATION COMPLETED")
        print("=" * 70)
        return 0
    else:
        print("✗ GENERATION FAILED")
        print("=" * 70)
        return 1


if __name__ == "__main__":
    sys.exit(main())
