#!/usr/bin/env python3
"""Generate concrete Mimic run files for tests.

The test suite owns small fixture *recipes* by scope, but Mimic runtime
validation requires concrete model and simulation package names in every run
file. This script materializes those run files for the selected MODEL and
SIMULATION under build/generated/test_inputs/.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import yaml
from discovery import REPO_ROOT

DEFAULT_MODEL = "sage"
DEFAULT_SIMULATION = "millennium"
OUTPUT_ROOT = REPO_ROOT / "build" / "generated" / "test_inputs"


def selected_model() -> str:
    return os.environ.get("MODEL") or DEFAULT_MODEL


def selected_simulation() -> str:
    return os.environ.get("SIMULATION") or os.environ.get("SIM") or DEFAULT_SIMULATION


def rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT))


def require_file(path: Path, label: str) -> Path:
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")
    return path


def require_dir(path: Path, label: str) -> Path:
    if not path.is_dir():
        raise FileNotFoundError(f"{label} not found: {path}")
    return path


def plot_profile(model_root: Path, simulation: str) -> str:
    candidates = [
        model_root / "plots" / "profiles" / f"{simulation}_plot_profile.yaml",
        model_root / "plots" / "profiles" / "default.yaml",
    ]
    for candidate in candidates:
        if candidate.is_file():
            return rel(candidate)
    return ""


def test_simulation_config(simulation_root: Path, simulation: str) -> tuple[str, str, str]:
    """Return simulation name, path, and config for fast test runs.

    A simulation package may provide its own test-sized simulation metadata at
    simulations/<simulation>/_tests/input/test_simulation.yaml. Millennium also
    has the historical shared mini-catalog under tests/data/.
    """
    package_test_config = simulation_root / "_tests" / "input" / "test_simulation.yaml"
    if package_test_config.is_file():
        return f"test_{simulation}", rel(simulation_root), rel(package_test_config)

    shared_millennium_config = REPO_ROOT / "tests" / "data" / "test_simulation.yaml"
    if simulation == "millennium" and shared_millennium_config.is_file():
        return "test_millennium", "tests/data", rel(shared_millennium_config)

    production_config = simulation_root / "simulation_info.yaml"
    require_file(production_config, "simulation config")
    return simulation, rel(simulation_root), rel(production_config)


def base_run_config(model: str, simulation: str) -> dict[str, Any]:
    model_root = require_dir(REPO_ROOT / "models" / model, "model package")
    simulation_root = require_dir(REPO_ROOT / "simulations" / simulation, "simulation package")

    model_properties = require_file(model_root / "model_properties.yaml", "model properties")
    halo_properties = require_file(
        simulation_root / "halo_properties.yaml", "simulation halo properties"
    )
    sim_name, sim_path, sim_config = test_simulation_config(simulation_root, simulation)

    config: dict[str, Any] = {
        "model": {
            "name": model,
            "path": rel(model_root),
            "model_properties": rel(model_properties),
        },
        "simulation": {
            "name": sim_name,
            "path": sim_path,
            "config": sim_config,
            "halo_properties": rel(halo_properties),
        },
        "output": {},
        "SubSteps": 1,
        "modules": {
            "parameters": {},
        },
    }

    profile = plot_profile(model_root, simulation)
    if profile:
        config["plotting"] = {"profile": profile}

    return config


def write_yaml(path: Path, config: dict[str, Any], title: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write("#" + "=" * 77 + "\n")
        handle.write(f"# {title}\n")
        handle.write("# Auto-generated by scripts/generate_test_inputs.py; do not edit.\n")
        handle.write("#" + "=" * 77 + "\n\n")
        yaml.safe_dump(config, handle, default_flow_style=False, sort_keys=False)


def write_run(
    path: Path,
    base: dict[str, Any],
    *,
    title: str,
    output_format: str,
    output_directory: str,
    output_filename: str,
    snapshot_list: list[int],
) -> None:
    config = dict(base)
    config["output"] = {
        "output_filename": output_filename,
        "output_directory": output_directory,
        "output_format": output_format,
        "snapshot_list": snapshot_list,
    }
    write_yaml(path, config, title)


def generation_root(model: str, simulation: str) -> Path:
    return OUTPUT_ROOT / model / simulation


def generate() -> None:
    model = selected_model()
    simulation = selected_simulation()
    output_root = generation_root(model, simulation)
    base = base_run_config(model, simulation)

    write_run(
        output_root / "core" / "test_binary.yaml",
        base,
        title="Mimic Core Test Run - Binary",
        output_format="binary",
        output_directory="./tests/data/output/binary/",
        output_filename="model",
        snapshot_list=[63],
    )
    write_run(
        output_root / "core" / "test_hdf5.yaml",
        base,
        title="Mimic Core Test Run - HDF5",
        output_format="hdf5",
        output_directory="./tests/data/output/hdf5/",
        output_filename="model",
        snapshot_list=[63],
    )

    simulation_dir = output_root / "simulations" / simulation
    write_run(
        simulation_dir / "test_binary.yaml",
        base,
        title=f"Mimic {simulation} Simulation Test Run - Binary",
        output_format="binary",
        output_directory="./tests/data/output/binary/",
        output_filename="model",
        snapshot_list=[63],
    )
    write_run(
        simulation_dir / "test_hdf5.yaml",
        base,
        title=f"Mimic {simulation} Simulation Test Run - HDF5",
        output_format="hdf5",
        output_directory="./tests/data/output/hdf5/",
        output_filename="model",
        snapshot_list=[63],
    )
    if simulation == "millennium":
        write_run(
            simulation_dir / "test_uniquegalid.yaml",
            base,
            title="Mimic Millennium UniqueGalaxyID Test Run",
            output_format="binary",
            output_directory="./tests/data/output/binary/",
            output_filename="model_uniquegalid",
            snapshot_list=[62, 63],
        )

    manifest = {
        "generated_by": "scripts/generate_test_inputs.py",
        "model": model,
        "simulation": simulation,
    }
    with (output_root / "manifest.json").open("w", encoding="utf-8") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")

    print(f"Generated test inputs under {rel(output_root)}")


if __name__ == "__main__":
    generate()
