#!/usr/bin/env python3
"""
Module Registry Generator for Mimic

Generates module registration code, event contract headers, and test configurations
from module_info.yaml metadata files. Eliminates manual synchronization and
implements the metadata-driven module architecture including the event system.

Usage:
    MODEL=sage python3 scripts/generate_module_registry.py [--dry-run] [--verbose]

Reads:
    models/<MODEL>/module_info.yaml
    models/<MODEL>/shared/module_info.yaml
    models/<MODEL>/modules/*/module_info.yaml

Generates:
    src/module_system/generated/module_init.c      - Module registration code
    src/module_system/generated/event_contracts.h  - Event ID enums and module IDs
    tests/generated/module_sources.txt               - Module source list for the unit-test runner
    build/generated/module_registry_hash.txt         - Validation hash

Exit codes:
    0 - Success
    1 - Generation failed (validation errors, I/O errors)

Author: Module Metadata System
"""

import argparse
import hashlib
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple  # noqa: F401

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install PyYAML", file=sys.stderr)
    sys.exit(1)

from discovery import (
    REPO_ROOT,
    generated_module_dir,
    halo_property_files,
    model_property_files,
    module_metadata_files,
    rel,
    standalone_module_files,
    test_property_files,
)

# ==============================================================================
# COLOR OUTPUT
# ==============================================================================

# ANSI color codes (disabled if not a TTY)
if sys.stdout.isatty():
    COLOR_RED = "\033[91m"
    COLOR_YELLOW = "\033[93m"
    COLOR_RESET = "\033[0m"
else:
    COLOR_RED = ""
    COLOR_YELLOW = ""
    COLOR_RESET = ""


def print_error(msg: str) -> None:
    """Print error message in red."""
    print(f"{COLOR_RED}ERROR: {msg}{COLOR_RESET}", file=sys.stderr)


def print_warning(msg: str) -> None:
    """Print warning message in yellow."""
    print(f"{COLOR_YELLOW}WARNING: {msg}{COLOR_RESET}")


# ==============================================================================
# PATHS
# ==============================================================================

# Output files
MODULE_INIT_C = generated_module_dir() / "module_init.c"
EVENT_CONTRACTS_H = generated_module_dir() / "event_contracts.h"
MODULE_SOURCES_TXT = REPO_ROOT / "tests" / "generated" / "module_sources.txt"
MODULE_HASH_FILE = REPO_ROOT / "build" / "generated" / "module_registry_hash.txt"

# ==============================================================================
# HEADER GENERATION (consistent across all generators)
# ==============================================================================


def generate_c_header(metadata_hash: str, description: str = "") -> str:
    """Generate consistent C header for all generated files."""
    selected_model = os.environ.get("MODEL") or "<MODEL>"
    header = "/* AUTO-GENERATED CODE - DO NOT EDIT\n"
    header += " *\n"
    header += " * Generated by: scripts/generate_module_registry.py\n"
    header += " *\n"
    header += " * Source: configured module roots\n"
    if description:
        header += " *\n"
        for line in description.split("\n"):
            header += f" * {line}\n" if line else " *\n"
    header += " *\n"
    header += f" * Source MD5: {metadata_hash}\n"
    header += f" * To regenerate: make MODEL={selected_model} generate\n"
    header += " */\n"
    return header


def generate_makefile_header(metadata_hash: str) -> str:
    """Generate consistent Makefile header for all generated files."""
    selected_model = os.environ.get("MODEL") or "<MODEL>"
    header = "# AUTO-GENERATED CODE - DO NOT EDIT\n"
    header += "#\n"
    header += "# Generated by: scripts/generate_module_registry.py\n"
    header += "#\n"
    header += "# Source: configured module roots\n"
    header += "#\n"
    header += f"# Source MD5: {metadata_hash}\n"
    header += f"# To regenerate: make MODEL={selected_model} generate\n"
    return header


# ==============================================================================
# MODULE DISCOVERY
# ==============================================================================


def load_module_metadata(module_dir: Path) -> Optional[Dict[str, Any]]:
    """Load module_info.yaml from module directory."""
    yaml_path = module_dir / "module_info.yaml"

    if not yaml_path.exists():
        return None

    try:
        with open(yaml_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
            if data is None:
                return None
            module = data.get("module", None)
            if module:
                # Add module directory path for reference
                module["_module_dir"] = module_dir
                module["_pattern"] = "directory"

                # Build sources list. Utility collections do not compile into
                # runtime modules.
                name = module["name"]
                sources = [] if module.get("is_utility", False) else [f"{name}.c"]

                if "additional_files" in module:
                    # Add any additional .c files
                    additional = module["additional_files"]
                    sources.extend([f for f in additional if f.endswith(".c")])

                module["sources"] = sources

            return module
    except yaml.YAMLError as e:
        print(f"ERROR: Failed to parse {yaml_path}: {e}", file=sys.stderr)
        return None


def create_standalone_module_metadata(c_file: Path) -> Dict[str, Any]:
    """Create minimal metadata for a package-local standalone module."""
    module_name = c_file.stem
    return {
        "name": module_name,
        "display_name": module_name.replace("_", " ").title(),
        "version": "1.0.0",
        "sources": [c_file.name],
        "supported_processing_modes": [
            "process_full_halo",
            "process_per_event",
            "process_by_galaxy",
        ],
        "dependencies": {"properties": [], "parameters": []},
        "_module_dir": c_file.parent,
        "_pattern": "standalone",
        "_standalone_file": c_file,
    }


def discover_modules() -> List[Dict[str, Any]]:
    """Discover all modules from package metadata."""
    modules = []

    for yaml_path in module_metadata_files():
        metadata = load_module_metadata(yaml_path.parent)
        if metadata:
            modules.append(metadata)

    for c_file in standalone_module_files():
        modules.append(create_standalone_module_metadata(c_file))

    return modules


# ==============================================================================
# DEPENDENCY RESOLUTION
# ==============================================================================


def resolve_dependencies(
    modules: List[Dict[str, Any]],
) -> Optional[List[Dict[str, Any]]]:
    """Return modules in order (no automatic dependency resolution).

    Note: Modules must be listed in correct execution order in the
    input YAML configuration file. No topological sorting is performed.
    """
    return modules if modules else []


def validate_unique_module_names(modules: List[Dict[str, Any]]) -> List[str]:
    """Ensure directory and standalone modules do not define the same name."""
    errors: List[str] = []
    seen: Dict[str, Dict[str, Any]] = {}
    for module in modules:
        name = module["name"]
        if name in seen:
            first = seen[name].get("_module_dir")
            second = module.get("_standalone_file") or module.get("_module_dir")
            errors.append(
                f"Duplicate module name '{name}' discovered in {rel(Path(first))} "
                f"and {rel(Path(second))}"
            )
            continue
        seen[name] = module
    return errors


# ==============================================================================
# VALIDATION
# ==============================================================================

VALID_PROCESSING_MODES = {
    "process_full_halo",
    "process_per_event",
    "process_by_galaxy",
}


def load_valid_properties() -> set:
    """Load all valid property names from halo and galaxy property files."""
    valid_properties = set()

    # Load galaxy properties (test_property_files() adds fixture-owned
    # properties for test builds; it is empty for production builds).
    for galaxy_props_path in model_property_files() + test_property_files():
        try:
            with open(galaxy_props_path, "r", encoding="utf-8") as f:
                props_yaml = yaml.safe_load(f)
            for prop in props_yaml.get("galaxy_properties", []):
                valid_properties.add(prop["name"])
        except (OSError, yaml.YAMLError, KeyError, TypeError) as e:
            print_warning(f"Failed to load galaxy properties from {rel(galaxy_props_path)}: {e}")

    # Load halo properties
    for halo_props_path in halo_property_files():
        try:
            with open(halo_props_path, "r", encoding="utf-8") as f:
                halo_yaml = yaml.safe_load(f)
            for prop in halo_yaml.get("halo_properties", []):
                valid_properties.add(prop["name"])
        except (OSError, yaml.YAMLError, KeyError, TypeError) as e:
            print_warning(f"Failed to load halo properties from {rel(halo_props_path)}: {e}")

    return valid_properties


def validate_processing_modes(modules: List[Dict[str, Any]]) -> List[str]:
    """Verify runtime directory modules declare valid processing modes."""
    errors = []

    for module in modules:
        module_name = module["name"]
        # Utility collections do not require
        # module-owned runtime processing-mode metadata.
        if module.get("is_utility", False):
            continue

        if "supported_processing_modes" not in module:
            errors.append(
                f"{module_name}/module_info.yaml: Missing required field "
                f"'supported_processing_modes' for runtime module"
            )
            continue

        modes = module["supported_processing_modes"]
        if not isinstance(modes, list) or len(modes) == 0:
            errors.append(
                f"{module_name}/module_info.yaml: 'supported_processing_modes' "
                f"must be a non-empty list"
            )
            continue

        invalid_modes = [mode for mode in modes if mode not in VALID_PROCESSING_MODES]
        if invalid_modes:
            errors.append(
                f"{module_name}/module_info.yaml: Invalid processing mode(s) "
                f"{invalid_modes} in 'supported_processing_modes' "
                f"(expected subset of {sorted(VALID_PROCESSING_MODES)})"
            )

        if len(set(modes)) != len(modes):
            errors.append(
                f"{module_name}/module_info.yaml: Duplicate entries in "
                f"'supported_processing_modes': {modes}"
            )

    return errors


def validate_property_dependencies(
    modules: List[Dict[str, Any]], valid_properties: set
) -> List[str]:
    """
    Verify all module property dependencies exist in property metadata.

    Returns list of error messages (empty if all valid).
    """
    errors = []

    for module in modules:
        module_name = module["name"]
        declared_props = module.get("dependencies", {}).get("properties", [])

        for prop in declared_props:
            if prop not in valid_properties:
                errors.append(
                    f"{module_name}/module_info.yaml: Unknown property '{prop}' "
                    f"in dependencies.properties"
                )

    return errors


def validate_module_files(modules: List[Dict[str, Any]]) -> List[str]:
    """
    Verify all declared source files exist.

    Supports the generated runtime source list for each module package.

    Returns list of error messages (empty if all valid).
    """
    errors = []

    for module in modules:
        module_name = module["name"]
        module_dir = module.get("_module_dir")
        if not module_dir:
            continue

        # Check source files (required)
        for source in module.get("sources", []):
            source_path = module_dir / source
            if not source_path.exists():
                errors.append(
                    f"{module_name}/module_info.yaml: Source file '{source}' not found\n"
                    f"    Expected at: {source_path}"
                )

    return errors


def validate_test_files(modules: List[Dict[str, Any]]) -> List[str]:
    """
    Check that declared test files exist.

    Returns list of warning messages (not errors - tests may be planned).
    """
    warnings = []
    valid_test_types = {"unit", "integration", "scientific"}

    for module in modules:
        module_name = module["name"]
        module_dir = module.get("_module_dir")

        if not module_dir:
            continue

        tests = module.get("tests", {})

        for test_type, test_path in tests.items():
            # Validate test type key
            if test_type not in valid_test_types:
                warnings.append(
                    f"{module_name}: Unknown test type '{test_type}' "
                    f"(expected: {', '.join(sorted(valid_test_types))})"
                )
                continue

            test_paths = test_path if isinstance(test_path, list) else [test_path]
            for one_test_path in test_paths:
                if not one_test_path:
                    continue

                full_path = module_dir / one_test_path
                if not full_path.exists():
                    warnings.append(
                        f"{module_name}: Declared {test_type} test not found: {one_test_path}"
                    )

            if not test_paths:
                continue

    return warnings


# ==============================================================================
# EVENT SYSTEM HELPERS
# ==============================================================================


def module_name_to_id_macro(module_name: str) -> str:
    """Convert module name to MODULE_ID_ macro name."""
    return f"MODULE_ID_{module_name.upper()}"


def event_name_to_enum_constant(producer_name: str, event_name: str) -> str:
    """Convert producer name + event name to C enum constant."""
    return f"{producer_name.upper()}_EVENT_{event_name.upper()}"


def producer_name_to_enum_type(producer_name: str) -> str:
    """Convert producer module name to C enum type name (PascalCase + EventId)."""
    parts = producer_name.split("_")
    return "".join(p.capitalize() for p in parts) + "EventId"


def collect_event_info(modules: List[Dict[str, Any]]) -> Tuple[Dict[str, Any], List[str]]:
    """
    Collect and index event declarations from all modules.

    Returns:
        (event_info, errors) where event_info is a dict with:
            producer_ids: {module_name: int}  — assigned 1-indexed IDs for producers
            emits: {module_name: [{name, description}]}
            consumes: {module_name: [{producer, event}]}
        errors: list of error strings (empty if valid)
    """
    errors: List[str] = []
    emits: Dict[str, List[Dict[str, str]]] = {}
    consumes: Dict[str, List[Dict[str, str]]] = {}

    for module in modules:
        name = module["name"]
        events = module.get("events", {})
        if events is None:
            continue

        emit_list = events.get("emits", []) or []
        consume_list = events.get("consumes", []) or []

        if emit_list:
            emits[name] = emit_list
        if consume_list:
            consumes[name] = consume_list

    # Assign stable producer IDs (sorted by module name, 1-indexed)
    producer_ids = {name: idx + 1 for idx, name in enumerate(sorted(emits.keys()))}

    return {"producer_ids": producer_ids, "emits": emits, "consumes": consumes}, errors


def validate_event_declarations(
    modules: List[Dict[str, Any]], event_info: Dict[str, Any]
) -> List[str]:
    """
    Validate all event declarations across all modules.

    Rules enforced:
    - events.emits only valid for modules supporting process_full_halo
    - events.consumes only valid for modules supporting process_per_event
    - Emitted event names must be unique within a producer
    - Consumed (producer, event) pairs must be unique within a consumer
    - Each consumed producer must exist and declare the referenced event
    """
    errors: List[str] = []
    emits = event_info["emits"]
    consumes = event_info["consumes"]

    # Build lookup: {producer_name: {event_name}} for cross-reference validation
    all_emitted: Dict[str, set] = {
        prod: {e["name"] for e in events} for prod, events in emits.items()
    }

    # Index module metadata by name for quick lookup
    module_by_name: Dict[str, Dict[str, Any]] = {m["name"]: m for m in modules}

    # Validate producers
    for producer_name, emit_list in emits.items():
        module = module_by_name.get(producer_name, {})
        modes = module.get("supported_processing_modes", [])

        if "process_full_halo" not in modes:
            errors.append(
                f"{producer_name}/module_info.yaml: 'events.emits' is only valid for "
                f"modules that support process_full_halo; this module supports {modes}"
            )

        # Check for duplicate event names within a producer
        seen_names: set = set()
        for event in emit_list:
            event_name = event.get("name", "")
            if not event_name:
                errors.append(
                    f"{producer_name}/module_info.yaml: event in 'events.emits' "
                    f"is missing required 'name' field"
                )
                continue
            if event_name in seen_names:
                errors.append(
                    f"{producer_name}/module_info.yaml: duplicate event name "
                    f"'{event_name}' in 'events.emits'"
                )
            seen_names.add(event_name)

    # Validate consumers
    for consumer_name, consume_list in consumes.items():
        module = module_by_name.get(consumer_name, {})
        modes = module.get("supported_processing_modes", [])

        if "process_per_event" not in modes:
            errors.append(
                f"{consumer_name}/module_info.yaml: 'events.consumes' is only valid for "
                f"modules that support process_per_event; this module supports {modes}"
            )

        # Check for duplicate (producer, event) pairs within a consumer
        seen_pairs: set = set()
        for sub in consume_list:
            prod = sub.get("producer", "")
            event = sub.get("event", "")
            if not prod or not event:
                errors.append(
                    f"{consumer_name}/module_info.yaml: subscription in 'events.consumes' "
                    f"is missing required 'producer' or 'event' field"
                )
                continue
            pair = (prod, event)
            if pair in seen_pairs:
                errors.append(
                    f"{consumer_name}/module_info.yaml: duplicate subscription "
                    f"(producer='{prod}', event='{event}') in 'events.consumes'"
                )
            seen_pairs.add(pair)

            # Referenced producer must exist and declare the referenced event
            if prod not in all_emitted:
                errors.append(
                    f"{consumer_name}/module_info.yaml: subscribes to producer "
                    f"'{prod}' but that module does not declare any 'events.emits'"
                )
            elif event not in all_emitted[prod]:
                declared = sorted(all_emitted[prod])
                errors.append(
                    f"{consumer_name}/module_info.yaml: subscribes to event "
                    f"'{event}' on producer '{prod}', but that event is not declared; "
                    f"declared events: {declared}"
                )

    return errors


# ==============================================================================
# CODE GENERATION - event_contracts.h
# ==============================================================================


def generate_event_contracts_h(
    modules: List[Dict[str, Any]],
    event_info: Dict[str, Any],
    metadata_hash: str,
    output_path: Path,
    dry_run: bool = False,
) -> bool:
    """Generate the public event contracts header (module IDs + event enums)."""
    producer_ids = event_info["producer_ids"]
    emits = event_info["emits"]
    consumes = event_info["consumes"]

    lines: List[str] = []

    # Header comment
    header = generate_c_header(
        metadata_hash,
        "Public event contract definitions for module C code.\n"
        'Include as: #include "module_system/generated/event_contracts.h"',
    )
    lines.extend(header.splitlines())
    lines.append("")

    lines.append("#ifndef MIMIC_EVENT_CONTRACTS_H")
    lines.append("#define MIMIC_EVENT_CONTRACTS_H")
    lines.append("")
    lines.append('#include "module_interface.h"')
    lines.append("")

    if producer_ids:
        lines.append(
            "/* ========================================================================== */"
        )
        lines.append(
            "/* PRODUCER MODULE IDS                                                        */"
        )
        lines.append(
            "/* ========================================================================== */"
        )
        lines.append("")
        lines.append("/*")
        lines.append(
            " * Stable numeric IDs for producer modules, generated from sorted module names."
        )
        lines.append(
            " * Used in ModuleEvent.producer_module_id and EventSubscription.producer_module_id."
        )
        lines.append(" * These IDs are injected by the core; producers never set them manually.")
        lines.append(" */")
        lines.append("")
        for name in sorted(producer_ids.keys()):
            macro = module_name_to_id_macro(name)
            lines.append(f"#define {macro} {producer_ids[name]}")
        lines.append("")

    if emits:
        lines.append(
            "/* ========================================================================== */"
        )
        lines.append(
            "/* PER-PRODUCER EVENT ID ENUMS                                                */"
        )
        lines.append(
            "/* ========================================================================== */"
        )
        lines.append("")
        lines.append("/*")
        lines.append(" * Use these constants as the event_id argument to module_emit_event().")
        lines.append(" * IDs start at 1; 0 is reserved for 'unset'.")
        lines.append(" */")
        lines.append("")
        for producer_name in sorted(emits.keys()):
            emit_list = emits[producer_name]
            enum_type = producer_name_to_enum_type(producer_name)
            lines.append(f"enum {enum_type} {{")
            for idx, event in enumerate(emit_list, start=1):
                event_name = event["name"]
                constant = event_name_to_enum_constant(producer_name, event_name)
                desc = event.get("description", "")
                if desc:
                    lines.append(f"  {constant} = {idx}, /**< {desc} */")
                else:
                    lines.append(f"  {constant} = {idx},")
            lines.append(f"}};")
            lines.append("")

    lines.append("#endif /* MIMIC_EVENT_CONTRACTS_H */")
    lines.append("")

    content = "\n".join(lines)

    if dry_run:
        print("\n=== event_contracts.h (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================
# HASH COMPUTATION
# ==============================================================================


def compute_metadata_hash(modules: List[Dict[str, Any]]) -> str:
    """Compute MD5 hash of module-generation inputs."""
    md5 = hashlib.md5()

    generator_path = Path(__file__)
    md5.update(rel(generator_path).encode("utf-8"))
    md5.update(generator_path.read_bytes())

    # Sort by module name for consistent ordering
    sorted_modules = sorted(modules, key=lambda m: m["name"])

    for module in sorted_modules:
        if module.get("_pattern") == "standalone":
            c_file = module.get("_standalone_file")
            if c_file and c_file.exists():
                md5.update(f"standalone:{rel(c_file)}".encode("utf-8"))
                with open(c_file, "rb") as f:
                    md5.update(f.read())
            continue

        module_dir = module.get("_module_dir")
        if module_dir:
            yaml_path = module_dir / "module_info.yaml"
            if yaml_path.exists():
                with open(yaml_path, "rb") as f:
                    md5.update(f.read())

    return md5.hexdigest()


def load_saved_hash() -> str:
    """Load the previously saved module metadata hash.

    Returns:
        The saved hash, or empty string if not found.
    """
    if MODULE_HASH_FILE.exists():
        try:
            with open(MODULE_HASH_FILE, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("MODULE_HASH="):
                        return line.split("=", 1)[1].strip()
        except Exception:
            pass
    return ""


# ==============================================================================
# CODE GENERATION - module_init.c
# ==============================================================================


def generate_lifecycle_forward_declarations(modules: List[Dict[str, Any]]) -> List[str]:
    """Generate forward declarations for module lifecycle functions."""
    lines = []
    lines.append("/* ========================================================================== */")
    lines.append("/* FORWARD DECLARATIONS FOR MODULE LIFECYCLE FUNCTIONS                       */")
    lines.append("/* ========================================================================== */")
    lines.append("")
    lines.append("/*")
    lines.append(" * Forward declarations for module lifecycle functions.")
    lines.append(" * These functions are implemented in each module's .c file.")
    lines.append(" *")
    lines.append(" * Eliminates need for per-module header files.")
    lines.append(" */")
    lines.append("")

    for module in sorted(modules, key=lambda m: m["name"]):
        name = module["name"]
        lines.append(f"extern int {name}_init(void);")
        lines.append(
            f"extern int {name}_process(struct ModuleContext *ctx, struct Halo *halos, int ngal);"
        )
        lines.append(f"extern int {name}_cleanup(void);")
        lines.append("")

    return lines


def generate_module_struct_definitions(
    modules: List[Dict[str, Any]], event_info: Dict[str, Any]
) -> List[str]:
    """Generate static struct Module definitions for all modules."""
    producer_ids = event_info["producer_ids"]
    consumes = event_info["consumes"]
    emits = event_info["emits"]

    lines = []
    lines.append("/* ========================================================================== */")
    lines.append("/* MODULE STRUCT DEFINITIONS (auto-generated from module metadata)            */")
    lines.append("/* ========================================================================== */")
    lines.append("")
    lines.append("/*")
    lines.append(" * Module struct definitions generated from discovered module metadata.")
    lines.append(" * Each module struct connects lifecycle functions to the module registry.")
    lines.append(" *")
    lines.append(" * Directory modules use module_info.yaml; standalone modules derive minimal")
    lines.append(" * metadata from their package-local source file.")
    lines.append(" */")
    lines.append("")

    for module in sorted(modules, key=lambda m: m["name"]):
        name = module["name"]
        modes = module.get(
            "supported_processing_modes",
            ["process_full_halo", "process_per_event", "process_by_galaxy"],
        )
        num_modes = len(modes)

        # Event system fields
        module_id = producer_ids.get(name, 0)
        num_subscriptions = len(consumes.get(name, []))
        subscriptions_val = f"{name}_subscriptions" if num_subscriptions > 0 else "NULL"
        emit_list = emits.get(name, [])
        num_emitted = len(emit_list)
        emitted_ids_val = f"{name}_emitted_event_ids" if num_emitted > 0 else "NULL"

        lines.append(f"static struct Module {name}_module = {{")
        lines.append(f'    .name = "{name}",')
        lines.append(f"    .init = {name}_init,")
        lines.append(f"    .process = {name}_process,")
        lines.append(f"    .cleanup = {name}_cleanup,")
        lines.append(f"    .supported_processing_modes = {name}_supported_modes,")
        lines.append(f"    .num_supported_modes = {num_modes},")
        lines.append(f"    .module_id = {module_id},")
        lines.append(f"    .subscriptions = {subscriptions_val},")
        lines.append(f"    .num_subscriptions = {num_subscriptions},")
        lines.append(f"    .emitted_event_ids = {emitted_ids_val},")
        lines.append(f"    .num_emitted_events = {num_emitted}")
        lines.append("};")
        lines.append("")

    return lines


def generate_module_init_c(
    modules: List[Dict[str, Any]],
    event_info: Dict[str, Any],
    metadata_hash: str,
    output_path: Path,
    dry_run: bool = False,
) -> bool:
    """Generate module registration code."""

    # Filter out utilities (is_utility: true) - they're test-only, not runtime modules
    runtime_modules = [m for m in modules if not m.get("is_utility", False)]

    producer_ids = event_info["producer_ids"]
    emits = event_info["emits"]
    consumes = event_info["consumes"]

    lines = []

    # Header
    description = f"""To validate:
  make MODEL={os.environ.get('MODEL', 'sage')} validate-modules"""
    header = generate_c_header(metadata_hash, description)
    lines.extend(header.splitlines())
    lines.append("")

    # Includes
    lines.append('#include "module_registry.h"')
    lines.append('#include "module_interface.h"')
    if emits or consumes:
        lines.append('#include "event_contracts.h"')
    lines.append("")

    # Forward declarations for module lifecycle functions
    lines.extend(generate_lifecycle_forward_declarations(runtime_modules))

    # Generate processing mode arrays for each module
    lines.append("/* ========================================================================== */")
    lines.append("/* SUPPORTED PROCESSING MODES (Auto-generated from module metadata)          */")
    lines.append("/* ========================================================================== */")
    lines.append("")
    lines.append("/*")
    lines.append(" * These arrays define which processing modes each module supports:")
    lines.append(" * - PROCESSING_MODE_FULL_HALO: Module processes full halo array (ngal > 1)")
    lines.append(
        " * - PROCESSING_MODE_PER_EVENT: Module processes one event target at a time (ngal = 1)"
    )
    lines.append(" * - PROCESSING_MODE_BY_GALAXY: Module processes one galaxy at a time (ngal = 1)")
    lines.append(" *")
    lines.append(" * Generated from supported_processing_modes metadata.")
    lines.append(" * Runtime directory modules declare this in module_info.yaml; standalone")
    lines.append(" * modules inherit all processing modes.")
    lines.append(" *")
    lines.append(" * Modules reference these arrays in their Module struct initialization.")
    lines.append(" */")
    lines.append("")

    for module in sorted(runtime_modules, key=lambda m: m["name"]):
        name = module["name"]
        # Get supported modes from metadata (default to both if not specified)
        modes = module.get(
            "supported_processing_modes",
            ["process_full_halo", "process_per_event", "process_by_galaxy"],
        )

        # Convert mode strings to enum values
        mode_enums = []
        for mode in modes:
            if mode == "process_full_halo":
                mode_enums.append("PROCESSING_MODE_FULL_HALO")
            elif mode == "process_per_event":
                mode_enums.append("PROCESSING_MODE_PER_EVENT")
            elif mode == "process_by_galaxy":
                mode_enums.append("PROCESSING_MODE_BY_GALAXY")

        # Generate array
        mode_list = ", ".join(mode_enums)
        lines.append(f"const enum ProcessingMode {name}_supported_modes[] = {{{mode_list}}};")

    lines.append("")

    # Generate producer emit ID arrays (for emit-time validation in module_emit_event)
    producer_modules = {
        name: events
        for name, events in emits.items()
        if any(m["name"] == name for m in runtime_modules)
    }
    if producer_modules:
        lines.append(
            "/* ========================================================================== */"
        )
        lines.append(
            "/* PRODUCER EMIT ID ARRAYS (Auto-generated from module_info.yaml)            */"
        )
        lines.append(
            "/* ========================================================================== */"
        )
        lines.append("")
        lines.append("/*")
        lines.append(" * Emit ID arrays record which event IDs each producer module declared.")
        lines.append(" * module_emit_event() validates against these arrays at emit time so")
        lines.append(" * undeclared event IDs are rejected immediately rather than silently")
        lines.append(" * routing to no consumer.")
        lines.append(" *")
        lines.append(" * Generated from 'events.emits' sections in module_info.yaml.")
        lines.append(" */")
        lines.append("")
        for producer_name in sorted(producer_modules.keys()):
            emit_list = producer_modules[producer_name]
            id_list = ", ".join(
                str(event_name_to_enum_constant(producer_name, e["name"])) for e in emit_list
            )
            lines.append(f"static const int {producer_name}_emitted_event_ids[] = {{{id_list}}};")
            lines.append("")

    # Generate event subscription tables for consumers
    consumer_modules = {
        name: subs
        for name, subs in consumes.items()
        if any(m["name"] == name for m in runtime_modules)
    }
    if consumer_modules:
        lines.append(
            "/* ========================================================================== */"
        )
        lines.append(
            "/* EVENT SUBSCRIPTION TABLES (Auto-generated from module_info.yaml)          */"
        )
        lines.append(
            "/* ========================================================================== */"
        )
        lines.append("")
        lines.append("/*")
        lines.append(" * Subscription tables define which (producer, event) pairs each")
        lines.append(" * process_per_event consumer module is subscribed to.")
        lines.append(" * The dispatch loop checks these before calling consumer modules —")
        lines.append(" * no event-code filtering is needed in module C code.")
        lines.append(" *")
        lines.append(" * Generated from 'events.consumes' sections in module_info.yaml.")
        lines.append(" */")
        lines.append("")

        for consumer_name in sorted(consumer_modules.keys()):
            sub_list = consumer_modules[consumer_name]
            lines.append(
                f"static const struct EventSubscription {consumer_name}_subscriptions[] = {{"
            )
            for sub in sub_list:
                prod = sub["producer"]
                event = sub["event"]
                prod_id_macro = module_name_to_id_macro(prod)
                event_id_const = event_name_to_enum_constant(prod, event)
                lines.append(f"    {{")
                lines.append(f"        .producer_module_id = {prod_id_macro},")
                lines.append(f"        .event_id = {event_id_const},")
                lines.append(f'        .event_name = "{event}",')
                lines.append(f'        .producer_name = "{prod}",')
                lines.append(f"    }},")
            lines.append("};")
            lines.append("")

    # Module struct definitions
    lines.extend(generate_module_struct_definitions(runtime_modules, event_info))

    # Registration function
    lines.append("/* ========================================================================== */")
    lines.append("/* MODULE REGISTRATION                                                        */")
    lines.append("/* ========================================================================== */")
    lines.append("")
    lines.append("/**")
    lines.append(" * @brief Register all available physics modules")
    lines.append(" *")
    lines.append(f" * Modules registered: {len(runtime_modules)}")
    lines.append(" *")
    if runtime_modules:
        lines.append(" * Execution order (from config):")
        for i, module in enumerate(runtime_modules, 1):
            name = module["name"]
            properties = module.get("dependencies", {}).get("properties", [])

            if properties:
                props_str = ", ".join(properties)
                lines.append(f" * {i}. {name}: uses [{props_str}]")
            else:
                lines.append(f" * {i}. {name}: (no properties)")
    lines.append(" */")
    lines.append("void register_all_modules(void) {")

    if runtime_modules:
        lines.append("    /* Directly register module structs (no per-module functions) */")
        for module in runtime_modules:
            name = module["name"]
            properties = module.get("dependencies", {}).get("properties", [])

            # Add inline comment
            if properties:
                comment = f"  /* Uses: {', '.join(properties)} */"
            else:
                comment = ""

            lines.append(f"    module_registry_add(&{name}_module);{comment}")
    else:
        lines.append("    /* No modules to register */")

    lines.append("}")
    lines.append("")

    # Write file
    content = "\n".join(lines)

    if dry_run:
        print("=== module_init.c (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================


# ==============================================================================
# CODE GENERATION - module_sources.txt
# ==============================================================================


def generate_module_sources_list(
    modules: List[Dict[str, Any]],
    metadata_hash: str,
    output_path: Path,
    dry_run: bool = False,
) -> bool:
    """Generate the module source list consumed by tests/unit/run_tests.sh.

    Plain newline-separated paths ('#' comments allowed): the only consumer is
    the shell runner, so no make syntax is involved.
    """

    # Filter out utilities (is_utility: true) - they have no runtime source files
    runtime_modules = [m for m in modules if not m.get("is_utility", False)]

    lines = []

    # Header
    header = generate_makefile_header(metadata_hash)
    lines.extend(header.splitlines())
    lines.append("")

    # Module source files for unit testing, one per line
    lines.append("src/core/module_registry.c")
    for module in runtime_modules:
        module_dir = module.get("_module_dir")
        if module_dir:
            for source in module.get("sources", []):
                lines.append(rel(module_dir / source))
    lines.append(rel(MODULE_INIT_C))
    lines.append("")

    # Write file
    content = "\n".join(lines)

    if dry_run:
        print("\n=== module_sources.txt (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================
# CODE GENERATION - Hash File
# ==============================================================================


def generate_hash_file(metadata_hash: str, output_path: Path, dry_run: bool = False) -> bool:
    """Generate hash file for validation."""

    lines = []
    lines.append("# AUTO-GENERATED CODE - DO NOT EDIT")
    lines.append("#")
    lines.append("# Hash of all module metadata files for validation")
    lines.append("#")
    lines.append(f"# Source MD5: {metadata_hash}")
    lines.append(f"# To regenerate: make MODEL={os.environ.get('MODEL', 'sage')} generate")
    lines.append("")
    lines.append(f"MODULE_HASH={metadata_hash}")
    lines.append("")

    content = "\n".join(lines)

    if dry_run:
        print("\n=== module_registry_hash.txt (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================
# MAIN
# ==============================================================================


def main():
    """Main entry point."""

    parser = argparse.ArgumentParser(description="Generate module registration code")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated code without writing files",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()

    print("=" * 70)
    print("Module Registry Generation")
    print("=" * 70)
    print()

    # Discover modules
    modules = discover_modules()

    if not modules:
        print("WARNING: No module metadata found")
        print("         Empty registration code will be generated")
        # Continue with empty list to generate valid (but empty) code

    if modules:
        duplicate_errors = validate_unique_module_names(modules)
        if duplicate_errors:
            print_error("Duplicate module names:")
            for err in duplicate_errors:
                print(f"  - {err}", file=sys.stderr)
            return 1

        print(f"Found {len(modules)} module(s):")
        for module in modules:
            pattern = module.get("_pattern", "directory")
            suffix = " [standalone]" if pattern == "standalone" else ""
            print(f"  - {module['name']} ({module.get('version', '1.0.0')}){suffix}")
        print()

    # Resolve dependencies
    if modules:
        print("Resolving dependencies...")
        sorted_modules = resolve_dependencies(modules)
        if sorted_modules is None:
            print("ERROR: Dependency resolution failed", file=sys.stderr)
            return 1

        if args.verbose:
            print("Dependency order:")
            for i, module in enumerate(sorted_modules, 1):
                print(f"  {i}. {module['name']}")
        print()
    else:
        sorted_modules = []

    # ==========================================================================
    # VALIDATION
    # ==========================================================================

    if modules:
        print("Validating processing mode metadata...")
        processing_mode_errors = validate_processing_modes(modules)
        if processing_mode_errors:
            print_error("Invalid processing mode metadata:")
            for err in processing_mode_errors:
                print(f"  - {err}", file=sys.stderr)
            return 1
        print("✓ All runtime module processing modes valid")

        # Validate module source/header files exist
        print("Validating module files...")
        file_errors = validate_module_files(modules)
        if file_errors:
            print_error("Missing module files:")
            for err in file_errors:
                print(f"  - {err}", file=sys.stderr)
            return 1
        print(f"✓ All module files exist")

        # Validate property dependencies
        print("Validating property dependencies...")
        valid_properties = load_valid_properties()
        if not valid_properties:
            print_warning("No valid properties loaded - skipping property validation")
        else:
            prop_errors = validate_property_dependencies(modules, valid_properties)
            if prop_errors:
                print_error("Invalid property dependencies:")
                for err in prop_errors:
                    print(f"  - {err}", file=sys.stderr)
                return 1
            print(
                f"✓ All property dependencies valid ({len(valid_properties)} properties available)"
            )

        # Check test files (warning only - always shown, not just verbose)
        print("Checking declared test files...")
        test_warnings = validate_test_files(modules)
        if test_warnings:
            print_warning("Some declared tests not found:")
            for warn in test_warnings:
                print(f"  {COLOR_YELLOW}- {warn}{COLOR_RESET}")
            print(f"  {COLOR_YELLOW}(Tests may be planned but not yet implemented){COLOR_RESET}")
        else:
            print("✓ All declared test files exist")

        print()

    # ==========================================================================
    # EVENT SYSTEM VALIDATION
    # ==========================================================================

    print("Collecting event declarations...")
    event_info, event_collect_errors = collect_event_info(modules)
    if event_collect_errors:
        print_error("Event collection errors:")
        for err in event_collect_errors:
            print(f"  - {err}", file=sys.stderr)
        return 1

    producers = event_info["emits"]
    consumers = event_info["consumes"]
    if producers or consumers:
        print(f"  Producers: {sorted(producers.keys()) or '(none)'}")
        print(f"  Consumers: {sorted(consumers.keys()) or '(none)'}")

        print("Validating event declarations...")
        event_errors = validate_event_declarations(modules, event_info)
        if event_errors:
            print_error("Invalid event declarations:")
            for err in event_errors:
                print(f"  - {err}", file=sys.stderr)
            return 1
        print("✓ All event declarations valid")
    else:
        print("  (no event declarations found)")
    print()

    # Compute metadata hash
    metadata_hash = compute_metadata_hash(modules)
    if args.verbose:
        print(f"Metadata hash: {metadata_hash}")
        print()

    # Check if regeneration is needed (skip in dry-run mode)
    if not args.dry_run:
        saved_hash = load_saved_hash()
        if saved_hash == metadata_hash:
            print("✓ Module metadata unchanged - skipping regeneration")
            print(f"  Hash: {metadata_hash}")
            print()
            print("=" * 70)
            print("✓ SKIPPED (no changes)")
            print("=" * 70)
            return 0

        # Hash mismatch or missing - regeneration needed
        if saved_hash:
            print(f"Module metadata changed - regenerating...")
            print(f"  Old hash: {saved_hash}")
            print(f"  New hash: {metadata_hash}")
        else:
            print("No previous hash found - generating for first time...")
            print(f"  Hash: {metadata_hash}")
        print()

    # Generate files
    print("Generating files...")

    success = True
    success &= generate_event_contracts_h(
        sorted_modules, event_info, metadata_hash, EVENT_CONTRACTS_H, args.dry_run
    )
    success &= generate_module_init_c(
        sorted_modules, event_info, metadata_hash, MODULE_INIT_C, args.dry_run
    )
    success &= generate_module_sources_list(
        sorted_modules, metadata_hash, MODULE_SOURCES_TXT, args.dry_run
    )
    success &= generate_hash_file(metadata_hash, MODULE_HASH_FILE, args.dry_run)

    print()
    print("=" * 70)
    if success:
        if args.dry_run:
            print("✓ DRY RUN COMPLETED")
        else:
            print("✓ GENERATION COMPLETED")
        print("=" * 70)
        return 0
    else:
        print("✗ GENERATION FAILED")
        print("=" * 70)
        return 1


if __name__ == "__main__":
    sys.exit(main())
