#!/usr/bin/env python3
"""
Module Registry Generator for Mimic

Generates module registration code and test configurations from module_info.yaml
metadata files. This eliminates manual synchronization and implements the
metadata-driven module architecture.

Usage:
    python3 scripts/generate_module_registry.py [--dry-run] [--verbose]

Reads:
    src/modules/*/module_info.yaml

Generates:
    src/modules/_system/generated/module_init.c    - Module registration code
    tests/generated/module_sources.mk              - Test build configuration
    build/module_registry_hash.txt                 - Validation hash

Exit codes:
    0 - Success
    1 - Generation failed (validation errors, I/O errors)

Author: Module Metadata System (Phase 4.2.5)
Date: 2025-11-12
"""

import argparse
import hashlib
import sys
from graphlib import CycleError, TopologicalSorter
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML not installed. Run: pip install PyYAML", file=sys.stderr)
    sys.exit(1)

# ==============================================================================
# PATHS
# ==============================================================================

# Repository root (parent of scripts/)
REPO_ROOT = Path(__file__).parent.parent

# Module directory
MODULES_DIR = REPO_ROOT / "src" / "modules"

# Output files
MODULE_INIT_C = (
    REPO_ROOT / "src" / "modules" / "_system" / "generated" / "module_init.c"
)
MODULE_PARAMS_H = (
    REPO_ROOT / "src" / "modules" / "_system" / "generated" / "module_parameters.h"
)
MODULE_SOURCES_MK = REPO_ROOT / "tests" / "generated" / "module_sources.mk"
MODULE_HASH_FILE = REPO_ROOT / "build" / "module_registry_hash.txt"

# ==============================================================================
# HEADER GENERATION (consistent across all generators)
# ==============================================================================


def generate_c_header(metadata_hash: str, description: str = "") -> str:
    """Generate consistent C header for all generated files."""
    header = "/* AUTO-GENERATED CODE - DO NOT EDIT\n"
    header += " *\n"
    header += " * Generated by: scripts/generate_module_registry.py\n"
    header += " *\n"
    header += " * Source: src/modules/ * /module_info.yaml\n"
    if description:
        header += " *\n"
        for line in description.split("\n"):
            header += f" * {line}\n" if line else " *\n"
    header += " *\n"
    header += f" * Source MD5: {metadata_hash}\n"
    header += " * To regenerate: make generate\n"
    header += " */\n"
    return header


def generate_makefile_header(metadata_hash: str) -> str:
    """Generate consistent Makefile header for all generated files."""
    header = "# AUTO-GENERATED CODE - DO NOT EDIT\n"
    header += "#\n"
    header += "# Generated by: scripts/generate_module_registry.py\n"
    header += "#\n"
    header += "# Source: src/modules/*/module_info.yaml\n"
    header += "#\n"
    header += f"# Source MD5: {metadata_hash}\n"
    header += "# To regenerate: make generate\n"
    return header


# ==============================================================================
# MODULE DISCOVERY
# ==============================================================================


def load_module_metadata(module_dir: Path) -> Optional[Dict[str, Any]]:
    """Load module_info.yaml from module directory."""
    yaml_path = module_dir / "module_info.yaml"

    if not yaml_path.exists():
        return None

    try:
        with open(yaml_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
            if data is None:
                return None
            module = data.get("module", None)
            if module:
                # Add module directory path for reference
                module["_module_dir"] = module_dir
            return module
    except yaml.YAMLError as e:
        print(f"ERROR: Failed to parse {yaml_path}: {e}", file=sys.stderr)
        return None


def discover_modules() -> List[Dict[str, Any]]:
    """Discover all modules with module_info.yaml files."""
    modules = []

    if not MODULES_DIR.exists():
        print(f"ERROR: Module directory not found: {MODULES_DIR}", file=sys.stderr)
        return []

    for item in sorted(MODULES_DIR.iterdir()):
        if not item.is_dir():
            continue

        # Skip directories starting with underscore, except _system
        if item.name.startswith("_") and item.name != "_system":
            continue

        # Handle _system directory specially - only include test_fixture
        if item.name == "_system":
            test_fixture_dir = item / "test_fixture"
            if test_fixture_dir.exists() and test_fixture_dir.is_dir():
                metadata = load_module_metadata(test_fixture_dir)
                if metadata:
                    modules.append(metadata)
            continue

        # Regular module directory
        metadata = load_module_metadata(item)
        if metadata:
            modules.append(metadata)

    return modules


# ==============================================================================
# DEPENDENCY RESOLUTION
# ==============================================================================


def build_dependency_graph(modules: List[Dict[str, Any]]) -> Dict[str, List[str]]:
    """Build module dependency graph for topological sort."""

    graph = {}
    module_names = [m["name"] for m in modules]

    # Build module name -> provides mapping
    provides_map = {}
    for module in modules:
        name = module["name"]
        provides = module.get("dependencies", {}).get("provides", [])
        for prop in provides:
            if prop not in provides_map:
                provides_map[prop] = []
            provides_map[prop].append(name)

    # Build dependency edges
    for module in modules:
        name = module["name"]
        requires = module.get("dependencies", {}).get("requires", [])
        dependencies = []

        for req_prop in requires:
            if req_prop in provides_map:
                # This module depends on modules that provide req_prop
                for provider in provides_map[req_prop]:
                    if provider != name:  # Don't depend on self
                        dependencies.append(provider)

        graph[name] = list(set(dependencies))  # Remove duplicates

    return graph


def resolve_dependencies(
    modules: List[Dict[str, Any]],
) -> Optional[List[Dict[str, Any]]]:
    """Topologically sort modules by dependencies."""

    if not modules:
        return []

    try:
        graph = build_dependency_graph(modules)
    except Exception as e:
        print(f"ERROR: Failed to build dependency graph: {e}", file=sys.stderr)
        return None

    # Topological sort
    try:
        ts = TopologicalSorter(graph)
        sorted_names = list(ts.static_order())
    except CycleError as e:
        print(f"ERROR: Circular dependency detected: {e}", file=sys.stderr)
        return None

    # Create name -> module mapping
    module_map = {m["name"]: m for m in modules}

    # Return modules in dependency order
    sorted_modules = []
    for name in sorted_names:
        if name in module_map:
            sorted_modules.append(module_map[name])

    return sorted_modules


# ==============================================================================
# HASH COMPUTATION
# ==============================================================================


def compute_metadata_hash(modules: List[Dict[str, Any]]) -> str:
    """Compute MD5 hash of all module metadata files."""
    md5 = hashlib.md5()

    # Sort by module name for consistent ordering
    sorted_modules = sorted(modules, key=lambda m: m["name"])

    for module in sorted_modules:
        module_dir = module.get("_module_dir")
        if module_dir:
            yaml_path = module_dir / "module_info.yaml"
            if yaml_path.exists():
                with open(yaml_path, "rb") as f:
                    md5.update(f.read())

    return md5.hexdigest()


def load_saved_hash() -> str:
    """Load the previously saved module metadata hash.

    Returns:
        The saved hash, or empty string if not found.
    """
    if MODULE_HASH_FILE.exists():
        try:
            with open(MODULE_HASH_FILE, "r", encoding="utf-8") as f:
                for line in f:
                    if line.startswith("MODULE_HASH="):
                        return line.split("=", 1)[1].strip()
        except Exception:
            pass
    return ""


# ==============================================================================
# CODE GENERATION - module_init.c
# ==============================================================================


def generate_module_init_c(
    modules: List[Dict[str, Any]],
    metadata_hash: str,
    output_path: Path,
    dry_run: bool = False,
) -> bool:
    """Generate module registration code."""

    # Filter out utilities (is_utility: true) - they're test-only, not runtime modules
    runtime_modules = [m for m in modules if not m.get("is_utility", False)]

    lines = []

    # Header
    description = """To validate:
  make validate-modules"""
    header = generate_c_header(metadata_hash, description)
    lines.extend(header.splitlines())
    lines.append("")

    # Includes
    lines.append('#include "module_registry.h"')
    lines.append("")

    # Auto-generated module includes (sorted alphabetically)
    lines.append("/* Auto-generated module includes (sorted alphabetically) */")
    for module in sorted(runtime_modules, key=lambda m: m["name"]):
        module_dir = module.get("_module_dir")
        if module_dir:
            rel_path = module_dir.relative_to(MODULES_DIR)
            header_files = module.get("headers", [])
            for header in header_files:
                lines.append(f'#include "{rel_path}/{header}"')
    lines.append("")

    # Registration function
    lines.append("/**")
    lines.append(" * @brief Register all available physics modules")
    lines.append(" *")
    lines.append(f" * Modules registered: {len(runtime_modules)}")
    lines.append(" *")
    if runtime_modules:
        lines.append(" * Dependency order:")
        for i, module in enumerate(runtime_modules, 1):
            name = module["name"]
            provides = module.get("dependencies", {}).get("provides", [])
            requires = module.get("dependencies", {}).get("requires", [])

            if provides:
                provides_str = ", ".join(provides)
            else:
                provides_str = "(none)"

            if requires:
                requires_str = ", ".join(requires)
                lines.append(
                    f" * {i}. {name}: requires [{requires_str}] → provides [{provides_str}]"
                )
            else:
                lines.append(f" * {i}. {name}: provides [{provides_str}]")
    lines.append(" */")
    lines.append("void register_all_modules(void) {")

    if runtime_modules:
        lines.append("    /* Register in dependency-resolved order */")
        for module in runtime_modules:
            name = module["name"]
            register_func = module.get("register_function", f"{name}_register")
            provides = module.get("dependencies", {}).get("provides", [])
            requires = module.get("dependencies", {}).get("requires", [])

            # Add inline comment
            if provides and requires:
                comment = (
                    f"Requires: {', '.join(requires)} → Provides: {', '.join(provides)}"
                )
            elif provides:
                comment = f"Provides: {', '.join(provides)}"
            elif requires:
                comment = f"Requires: {', '.join(requires)}"
            else:
                comment = "No dependencies"

            lines.append(f"    {register_func}();  /* {comment} */")
    else:
        lines.append("    /* No modules to register */")

    lines.append("}")
    lines.append("")

    # Write file
    content = "\n".join(lines)

    if dry_run:
        print("=== module_init.c (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================
# CODE GENERATION - module_parameters.h
# ==============================================================================


def generate_parameter_metadata_h(
    modules: List[Dict[str, Any]],
    metadata_hash: str,
    output_path: Path,
    dry_run: bool = False,
) -> bool:
    """Generate parameter metadata header from module_info.yaml.

    This creates a compile-time lookup table of parameter metadata (ranges, types)
    that enables automatic parameter validation without hardcoding ranges in C code.

    Vision Principles:
    - Principle 3 (Metadata-Driven): Parameters defined once in YAML
    - Principle 4 (Single Source of Truth): No range duplication in C code
    """

    # Filter runtime modules (utilities excluded)
    runtime_modules = [m for m in modules if not m.get("is_utility", False)]

    # Collect all parameters with metadata
    param_entries = []
    for module in runtime_modules:
        module_name = module["name"]
        parameters = module.get("parameters", [])

        for param in parameters:
            param_name = param["name"]
            param_type = param.get("type", "double")
            param_default = param.get("default", 0)
            param_range = param.get("range", [])

            # Determine range bounds
            has_min = 1 if len(param_range) >= 1 else 0
            has_max = 1 if len(param_range) >= 2 else 0
            range_min = float(param_range[0]) if has_min else 0.0
            range_max = float(param_range[1]) if has_max else 0.0

            # Convert default to float for storage (0.0 for string types)
            if param_type == "string":
                default_float = 0.0  # String defaults not stored in metadata
            else:
                default_float = float(param_default)

            param_entries.append(
                {
                    "module": module_name,
                    "name": param_name,
                    "type": param_type,
                    "default": default_float,
                    "range_min": range_min,
                    "range_max": range_max,
                    "has_min": has_min,
                    "has_max": has_max,
                }
            )

    lines = []

    # Header
    description = """This file provides compile-time parameter metadata for automatic
validation. Ranges are defined once in module_info.yaml (single
source of truth) and generated into this lookup table."""
    header = generate_c_header(metadata_hash, description)
    lines.extend(header.splitlines())
    lines.append("")
    lines.append("#ifndef MODULE_PARAMETERS_H")
    lines.append("#define MODULE_PARAMETERS_H")
    lines.append("")

    # Struct definition
    lines.append("/**")
    lines.append(" * @brief Parameter metadata for automatic validation and defaults")
    lines.append(" *")
    lines.append(" * Each entry represents a parameter from module_info.yaml with its")
    lines.append(
        " * default value and validation range. Used by module_get_double/int to"
    )
    lines.append(" * automatically provide defaults and validate parameter values.")
    lines.append(" *")
    lines.append(" * Vision Principle 4 (Single Source of Truth): Defaults and ranges")
    lines.append(" * defined once in module_info.yaml, not hardcoded in C.")
    lines.append(" */")
    lines.append("struct ModuleParameterMetadata {")
    lines.append(
        "    const char *module_name;  /* Module name (e.g., 'sage_infall') */"
    )
    lines.append(
        "    const char *param_name;   /* Parameter name (e.g., 'BaryonFrac') */"
    )
    lines.append("    const char *type;         /* Type: 'double', 'int', 'string' */")
    lines.append("    double default_value;     /* Default value from metadata */")
    lines.append("    double range_min;         /* Minimum valid value */")
    lines.append("    double range_max;         /* Maximum valid value */")
    lines.append(
        "    int has_min;              /* 1 if min constraint exists, 0 otherwise */"
    )
    lines.append(
        "    int has_max;              /* 1 if max constraint exists, 0 otherwise */"
    )
    lines.append("};")
    lines.append("")

    # Array declaration
    if param_entries:
        lines.append("/* Parameter metadata lookup table */")
        lines.append(
            "static const struct ModuleParameterMetadata MODULE_PARAMETER_METADATA[] = {"
        )

        # Generate entries sorted by module, then parameter name
        sorted_entries = sorted(param_entries, key=lambda x: (x["module"], x["name"]))
        for entry in sorted_entries:
            # Format with proper alignment for readability
            lines.append(
                f'    {{"{entry["module"]}", "{entry["name"]}", "{entry["type"]}", '
                f'{entry["default"]}, {entry["range_min"]}, {entry["range_max"]}, '
                f'{entry["has_min"]}, {entry["has_max"]}}},  '
                f'/* {entry["module"]}_{entry["name"]} = {entry["default"]} */'
            )

        lines.append("};")
        lines.append("")
        lines.append(
            f"#define NUM_MODULE_PARAMETERS {len(param_entries)}  /* Total parameters with metadata */"
        )
    else:
        lines.append("/* No parameters with metadata found */")
        lines.append(
            "static const struct ModuleParameterMetadata MODULE_PARAMETER_METADATA[] = {};"
        )
        lines.append("#define NUM_MODULE_PARAMETERS 0")

    lines.append("")
    lines.append("#endif /* MODULE_PARAMETERS_H */")
    lines.append("")

    # Write file
    content = "\n".join(lines)

    if dry_run:
        print("\n=== module_parameters.h (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================
# CODE GENERATION - module_sources.mk
# ==============================================================================


def generate_module_sources_mk(
    modules: List[Dict[str, Any]],
    metadata_hash: str,
    output_path: Path,
    dry_run: bool = False,
) -> bool:
    """Generate makefile fragment for test system."""

    # Filter out utilities (is_utility: true) - they have no runtime source files
    runtime_modules = [m for m in modules if not m.get("is_utility", False)]

    lines = []

    # Header
    header = generate_makefile_header(metadata_hash)
    lines.extend(header.splitlines())
    lines.append("")

    # Module source files
    lines.append("# Module source files for unit testing")
    lines.append("MODULE_SRCS = \\")
    lines.append("    $(SRC_DIR)/core/module_registry.c \\")

    # Add each module's source files
    for module in runtime_modules:
        module_dir = module.get("_module_dir")
        if module_dir:
            rel_path = module_dir.relative_to(REPO_ROOT / "src")
            sources = module.get("sources", [])
            for source in sources:
                lines.append(f"    $(SRC_DIR)/{rel_path}/{source} \\")

    # Add module_init.c last (no backslash)
    lines.append("    $(SRC_DIR)/modules/_system/generated/module_init.c")
    lines.append("")

    # Write file
    content = "\n".join(lines)

    if dry_run:
        print("\n=== module_sources.mk (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================
# CODE GENERATION - Hash File
# ==============================================================================


def generate_hash_file(
    metadata_hash: str, output_path: Path, dry_run: bool = False
) -> bool:
    """Generate hash file for validation."""

    lines = []
    lines.append("# AUTO-GENERATED CODE - DO NOT EDIT")
    lines.append("#")
    lines.append("# Hash of all module metadata files for validation")
    lines.append("#")
    lines.append(f"# Source MD5: {metadata_hash}")
    lines.append("# To regenerate: make generate")
    lines.append("")
    lines.append(f"MODULE_HASH={metadata_hash}")
    lines.append("")

    content = "\n".join(lines)

    if dry_run:
        print("\n=== module_registry_hash.txt (DRY RUN) ===")
        print(content)
        return True

    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"✓ Generated: {output_path.relative_to(REPO_ROOT)}")
        return True
    except Exception as e:
        print(f"ERROR: Failed to write {output_path}: {e}", file=sys.stderr)
        return False


# ==============================================================================
# MAIN
# ==============================================================================


def main():
    """Main entry point."""

    parser = argparse.ArgumentParser(description="Generate module registration code")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print generated code without writing files",
    )
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()

    print("=" * 70)
    print("Module Registry Generation")
    print("=" * 70)
    print()

    # Discover modules
    modules = discover_modules()

    if not modules:
        print("WARNING: No modules found with module_info.yaml files")
        print("         Empty registration code will be generated")
        # Continue with empty list to generate valid (but empty) code

    if modules:
        print(f"Found {len(modules)} module(s):")
        for module in modules:
            print(f"  - {module['name']} ({module.get('version', '1.0.0')})")
        print()

    # Resolve dependencies
    if modules:
        print("Resolving dependencies...")
        sorted_modules = resolve_dependencies(modules)
        if sorted_modules is None:
            print("ERROR: Dependency resolution failed", file=sys.stderr)
            return 1

        if args.verbose:
            print("Dependency order:")
            for i, module in enumerate(sorted_modules, 1):
                print(f"  {i}. {module['name']}")
        print()
    else:
        sorted_modules = []

    # Compute metadata hash
    metadata_hash = compute_metadata_hash(modules)
    if args.verbose:
        print(f"Metadata hash: {metadata_hash}")
        print()

    # Check if regeneration is needed (skip in dry-run mode)
    if not args.dry_run:
        saved_hash = load_saved_hash()
        if saved_hash == metadata_hash:
            print("✓ Module metadata unchanged - skipping regeneration")
            print(f"  Hash: {metadata_hash}")
            print()
            print("=" * 70)
            print("✓ SKIPPED (no changes)")
            print("=" * 70)
            return 0

        # Hash mismatch or missing - regeneration needed
        if saved_hash:
            print(f"Module metadata changed - regenerating...")
            print(f"  Old hash: {saved_hash}")
            print(f"  New hash: {metadata_hash}")
        else:
            print("No previous hash found - generating for first time...")
            print(f"  Hash: {metadata_hash}")
        print()

    # Generate files
    print("Generating files...")

    success = True
    success &= generate_module_init_c(
        sorted_modules, metadata_hash, MODULE_INIT_C, args.dry_run
    )
    success &= generate_parameter_metadata_h(
        sorted_modules, metadata_hash, MODULE_PARAMS_H, args.dry_run
    )
    success &= generate_module_sources_mk(
        sorted_modules, metadata_hash, MODULE_SOURCES_MK, args.dry_run
    )
    success &= generate_hash_file(metadata_hash, MODULE_HASH_FILE, args.dry_run)

    print()
    print("=" * 70)
    if success:
        if args.dry_run:
            print("✓ DRY RUN COMPLETED")
        else:
            print("✓ GENERATION COMPLETED")
        print("=" * 70)
        return 0
    else:
        print("✗ GENERATION FAILED")
        print("=" * 70)
        return 1


if __name__ == "__main__":
    sys.exit(main())
