#!/usr/bin/env python3
"""Generate concrete Mimic run files for tests.

The test suite owns small fixture *recipes* by scope, but Mimic runtime
validation requires concrete model and simulation package names in every run
file. This script materializes those run files for the selected MODEL and
SIMULATION under build/generated/test_inputs/.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

import yaml
from discovery import REPO_ROOT, makefile_default, production_test_config_enabled, rel

OUTPUT_ROOT = REPO_ROOT / "build" / "generated" / "test_inputs"


def selected_model() -> str:
    return os.environ.get("MODEL") or makefile_default("DEFAULT_MODEL", "sage16")


def selected_simulation() -> str:
    return (
        os.environ.get("SIMULATION")
        or os.environ.get("SIM")
        or makefile_default("DEFAULT_SIMULATION", "mini-millennium")
    )


def require_file(path: Path, label: str) -> Path:
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")
    return path


def require_dir(path: Path, label: str) -> Path:
    if not path.is_dir():
        raise FileNotFoundError(f"{label} not found: {path}")
    return path


def test_simulation_config(simulation_root: Path, simulation: str) -> str:
    """Return a test-sized simulation config path for fast test runs.

    Full-validation micro-Uchuu packages use their production simulation
    metadata so the model test suite exercises the shipped reader paths. Other
    simulation packages may provide a test-sized simulation metadata file at
    simulations/<simulation>/_tests/input/test_simulation.yaml. This keeps fast
    core/model tests independent of production catalog size while still compiling
    against the selected simulation package.

    mini-Millennium has a shared single-file mini-catalog under tests/data/.
    Simulations without package-local fixtures fall back to production
    simulation_info.yaml; generated run YAML then applies input overrides to
    cap the file range. Production-scale packages should provide a fixture here.
    """
    production_config = simulation_root / "simulation_info.yaml"
    if production_test_config_enabled(simulation):
        require_file(production_config, "simulation config")
        return rel(production_config)

    package_test_config = simulation_root / "_tests" / "input" / "test_simulation.yaml"
    if package_test_config.is_file():
        return rel(package_test_config)

    shared_mini_millennium_config = REPO_ROOT / "tests" / "data" / "test_simulation.yaml"
    if simulation == "mini-millennium" and shared_mini_millennium_config.is_file():
        return rel(shared_mini_millennium_config)

    require_file(production_config, "simulation config")
    return rel(production_config)


def base_run_config(model: str, simulation: str) -> dict[str, Any]:
    model_root = require_dir(REPO_ROOT / "models" / model, "model package")
    simulation_root = require_dir(REPO_ROOT / "simulations" / simulation, "simulation package")

    require_file(model_root / "model_properties.yaml", "model properties")
    require_file(simulation_root / "halo_properties.yaml", "simulation halo properties")
    sim_config = test_simulation_config(simulation_root, simulation)

    config: dict[str, Any] = {
        "model": {
            "name": model,
        },
        "simulation": {
            "name": simulation,
            "config": sim_config,
        },
        "output": {},
        "SubSteps": 1,
        "modules": {
            "parameters": {},
        },
    }

    return config


def write_yaml(path: Path, config: dict[str, Any], title: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write("#" + "=" * 77 + "\n")
        handle.write(f"# {title}\n")
        handle.write("# Auto-generated by scripts/generate_test_inputs.py; do not edit.\n")
        handle.write("#" + "=" * 77 + "\n\n")
        yaml.safe_dump(config, handle, default_flow_style=False, sort_keys=False)


def write_run(
    path: Path,
    base: dict[str, Any],
    *,
    title: str,
    output_format: str,
    output_directory: str,
    output_filename: str,
    snapshot_list: list[int],
    input_overrides: dict[str, Any] | None = None,
    output_overrides: dict[str, Any] | None = None,
) -> None:
    config = dict(base)
    if input_overrides:
        config["input"] = input_overrides
    config["output"] = {
        "output_filename": output_filename,
        "output_directory": output_directory,
        "output_format": output_format,
        "snapshot_list": snapshot_list,
    }
    if output_overrides:
        config["output"].update(output_overrides)
    write_yaml(path, config, title)


def generation_root(model: str, simulation: str) -> Path:
    return OUTPUT_ROOT / model / simulation


def last_snapshot_index(sim_config_rel: str) -> int:
    """Return the last snapshot index from the simulation's scale-factor list.

    Test inputs must request snapshots that exist for the selected simulation
    package, whatever its snapshot count -- nothing here assumes the
    64-snapshot Millennium convention.
    """
    config = yaml.safe_load((REPO_ROOT / sim_config_rel).read_text(encoding="utf-8"))
    a_list_rel = (config.get("input") or {}).get("snapshot_list_file")
    if not a_list_rel:
        raise ValueError(f"simulation config {sim_config_rel} lacks input.snapshot_list_file")
    a_list = REPO_ROOT / a_list_rel
    count = sum(
        1 for raw in a_list.read_text(encoding="utf-8").splitlines() if raw.split("#", 1)[0].strip()
    )
    if count < 2:
        raise ValueError(f"snapshot list {a_list} has fewer than 2 snapshots")
    return count - 1


def generate() -> None:
    model = selected_model()
    simulation = selected_simulation()
    output_root = generation_root(model, simulation)
    base = base_run_config(model, simulation)

    # All generated test runs cap the file range to a single file so tests stay
    # fast regardless of how many files the production catalogue has. For
    # full-validation micro-Uchuu packages, the simulation_info.yaml provides
    # the production paths and tree format; the single-file cap keeps run time
    # bounded. For other packages, this overrides the test fixture or production
    # range to the same single-file limit.
    test_input = {"first_file": 0, "last_file": 0}

    # Snapshot indices derive from the selected simulation's a_list (last and
    # second-last snapshots) rather than hardcoding the mini-Millennium 63.
    last_snap = last_snapshot_index(base["simulation"]["config"])

    write_run(
        output_root / "core" / "test_binary.yaml",
        base,
        title="Mimic Core Test Run - Binary",
        output_format="binary",
        output_directory="./tests/data/output/binary/",
        output_filename="model",
        snapshot_list=[last_snap],
        input_overrides=test_input,
    )
    write_run(
        output_root / "core" / "test_hdf5.yaml",
        base,
        title="Mimic Core Test Run - HDF5",
        output_format="hdf5",
        output_directory="./tests/data/output/hdf5/",
        output_filename="model",
        snapshot_list=[last_snap],
        input_overrides=test_input,
    )

    simulation_dir = output_root / "simulations" / simulation
    write_run(
        simulation_dir / "test_binary.yaml",
        base,
        title=f"Mimic {simulation} Simulation Test Run - Binary",
        output_format="binary",
        output_directory="./tests/data/output/binary/",
        output_filename="model",
        snapshot_list=[last_snap],
        input_overrides=test_input,
    )
    write_run(
        simulation_dir / "test_hdf5.yaml",
        base,
        title=f"Mimic {simulation} Simulation Test Run - HDF5",
        output_format="hdf5",
        output_directory="./tests/data/output/hdf5/",
        output_filename="model",
        snapshot_list=[last_snap],
        input_overrides=test_input,
    )
    write_run(
        simulation_dir / "test_uniquegalid.yaml",
        base,
        title=f"Mimic {simulation} UniqueGalaxyID Test Run",
        output_format="binary",
        output_directory="./tests/data/output/binary/",
        output_filename="model_uniquegalid",
        snapshot_list=[last_snap - 1, last_snap],
        input_overrides=test_input,
    )

    manifest = {
        "generated_by": "scripts/generate_test_inputs.py",
        "model": model,
        "simulation": simulation,
    }
    with (output_root / "manifest.json").open("w", encoding="utf-8") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")

    print(f"Generated test inputs under {rel(output_root)}")


if __name__ == "__main__":
    generate()
