#!/usr/bin/env python3
"""
Generate test registry from module metadata.

This script scans all module_info.yaml files and generates test manifests
that allow the test runners to automatically discover and run module tests.

Usage:
    python scripts/generate_test_registry.py

Generates:
    build/generated_test_lists/unit_tests.txt        - Unit test paths
    build/generated_test_lists/integration_tests.txt - Integration test paths
    build/generated_test_lists/scientific_tests.txt  - Scientific test paths
    build/generated_test_lists/test_registry_hash.txt - Validation hash

Author: Mimic Development Team
Date: 2025-11-12
Phase: Phase 4.2 (Test Architecture Refactor)
"""

import hashlib
import sys
import yaml
from pathlib import Path


def generate_test_registry():
    """Generate test registry from module metadata."""

    print("Generating test registry...")
    print("=" * 70)

    # Paths
    repo_root = Path(__file__).parent.parent
    module_dir = repo_root / "src" / "modules"
    output_dir = repo_root / "build" / "generated_test_lists"

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    # Collect tests from all modules
    unit_tests = []
    integration_tests = []
    scientific_tests = []

    # Track modules for summary
    modules_found = []
    modules_with_tests = []

    # Scan for module metadata
    for module_info_file in sorted(module_dir.glob("*/module_info.yaml")):
        module_path = module_info_file.parent
        module_name = module_path.name

        # Skip template module
        if module_name == "_template":
            continue

        # Load metadata
        try:
            with open(module_info_file) as f:
                metadata = yaml.safe_load(f)
        except Exception as e:
            print(f"WARNING: Failed to load {module_info_file}: {e}")
            continue

        modules_found.append(module_name)

        # Get test declarations
        tests = metadata.get('module', {}).get('tests', {})

        has_tests = False

        # Unit tests
        if 'unit' in tests:
            unit_test_file = tests['unit']
            unit_test_path = module_path / unit_test_file
            if unit_test_path.exists():
                # Store relative path from repo root
                rel_path = unit_test_path.relative_to(repo_root)
                unit_tests.append(str(rel_path))
                has_tests = True
            else:
                print(f"WARNING: {module_name} declares unit test '{unit_test_file}' but file not found")

        # Integration tests
        if 'integration' in tests:
            integration_test_file = tests['integration']
            integration_test_path = module_path / integration_test_file
            if integration_test_path.exists():
                rel_path = integration_test_path.relative_to(repo_root)
                integration_tests.append(str(rel_path))
                has_tests = True
            else:
                print(f"WARNING: {module_name} declares integration test '{integration_test_file}' but file not found")

        # Scientific tests
        if 'scientific' in tests:
            scientific_test_file = tests['scientific']
            scientific_test_path = module_path / scientific_test_file
            if scientific_test_path.exists():
                rel_path = scientific_test_path.relative_to(repo_root)
                scientific_tests.append(str(rel_path))
                has_tests = True
            else:
                print(f"WARNING: {module_name} declares scientific test '{scientific_test_file}' but file not found")

        if has_tests:
            modules_with_tests.append(module_name)

    # Write test manifests
    unit_tests_file = output_dir / "unit_tests.txt"
    with open(unit_tests_file, 'w') as f:
        f.write("# Auto-generated unit test registry\n")
        f.write("# DO NOT EDIT - Generated by scripts/generate_test_registry.py\n")
        f.write(f"# Found {len(unit_tests)} unit test(s)\n\n")
        for test_path in unit_tests:
            f.write(f"{test_path}\n")

    integration_tests_file = output_dir / "integration_tests.txt"
    with open(integration_tests_file, 'w') as f:
        f.write("# Auto-generated integration test registry\n")
        f.write("# DO NOT EDIT - Generated by scripts/generate_test_registry.py\n")
        f.write(f"# Found {len(integration_tests)} integration test(s)\n\n")
        for test_path in integration_tests:
            f.write(f"{test_path}\n")

    scientific_tests_file = output_dir / "scientific_tests.txt"
    with open(scientific_tests_file, 'w') as f:
        f.write("# Auto-generated scientific test registry\n")
        f.write("# DO NOT EDIT - Generated by scripts/generate_test_registry.py\n")
        f.write(f"# Found {len(scientific_tests)} scientific test(s)\n\n")
        for test_path in scientific_tests:
            f.write(f"{test_path}\n")

    # Generate validation hash
    hash_content = "\n".join(sorted(unit_tests + integration_tests + scientific_tests))
    registry_hash = hashlib.md5(hash_content.encode()).hexdigest()

    hash_file = output_dir / "test_registry_hash.txt"
    with open(hash_file, 'w') as f:
        f.write(f"{registry_hash}\n")

    # Print summary
    print()
    print(f"Found {len(modules_found)} module(s):")
    for module in modules_found:
        marker = "✓" if module in modules_with_tests else " "
        print(f"  [{marker}] {module}")

    print()
    print("Test registry summary:")
    print(f"  Unit tests:        {len(unit_tests)}")
    print(f"  Integration tests: {len(integration_tests)}")
    print(f"  Scientific tests:  {len(scientific_tests)}")

    print()
    print("Generated files:")
    print(f"  ✓ {unit_tests_file.relative_to(repo_root)}")
    print(f"  ✓ {integration_tests_file.relative_to(repo_root)}")
    print(f"  ✓ {scientific_tests_file.relative_to(repo_root)}")
    print(f"  ✓ {hash_file.relative_to(repo_root)}")

    print()
    print("=" * 70)
    print("✓ TEST REGISTRY GENERATION COMPLETED")
    print("=" * 70)

    return 0


if __name__ == "__main__":
    sys.exit(generate_test_registry())
